//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventario.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ServiceSoap")]
    public interface ServiceSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        Inventario.ServiceReference1.HelloWorldResponse HelloWorld(Inventario.ServiceReference1.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name usuario from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/escribirMemo", ReplyAction="*")]
        Inventario.ServiceReference1.escribirMemoResponse escribirMemo(Inventario.ServiceReference1.escribirMemoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/estado", ReplyAction="*")]
        int estado();
        
        // CODEGEN: Generating message contract since element name obtenerMemosGenralesResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/obtenerMemosGenrales", ReplyAction="*")]
        Inventario.ServiceReference1.obtenerMemosGenralesResponse obtenerMemosGenrales(Inventario.ServiceReference1.obtenerMemosGenralesRequest request);
        
        // CODEGEN: Generating message contract since element name cotizacion from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/guardarCotizacion", ReplyAction="*")]
        Inventario.ServiceReference1.guardarCotizacionResponse guardarCotizacion(Inventario.ServiceReference1.guardarCotizacionRequest request);
        
        // CODEGEN: Generating message contract since element name listaCotizacionesResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/listaCotizaciones", ReplyAction="*")]
        Inventario.ServiceReference1.listaCotizacionesResponse listaCotizaciones(Inventario.ServiceReference1.listaCotizacionesRequest request);
        
        // CODEGEN: Generating message contract since element name vendedor from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/obtenerFactura", ReplyAction="*")]
        Inventario.ServiceReference1.obtenerFacturaResponse obtenerFactura(Inventario.ServiceReference1.obtenerFacturaRequest request);
        
        // CODEGEN: Generating message contract since element name indicadoresEconomicosResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/indicadoresEconomicos", ReplyAction="*")]
        Inventario.ServiceReference1.indicadoresEconomicosResponse indicadoresEconomicos(Inventario.ServiceReference1.indicadoresEconomicosRequest request);
        
        // CODEGEN: Generating message contract since element name dolar from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/setearIndicadoresEconomicos", ReplyAction="*")]
        Inventario.ServiceReference1.setearIndicadoresEconomicosResponse setearIndicadoresEconomicos(Inventario.ServiceReference1.setearIndicadoresEconomicosRequest request);
        
        // CODEGEN: Generating message contract since element name factura from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ingresarFacturaLiberada", ReplyAction="*")]
        Inventario.ServiceReference1.ingresarFacturaLiberadaResponse ingresarFacturaLiberada(Inventario.ServiceReference1.ingresarFacturaLiberadaRequest request);
        
        // CODEGEN: Generating message contract since element name fecha from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ingresarFacturaPorCotizacion", ReplyAction="*")]
        Inventario.ServiceReference1.ingresarFacturaPorCotizacionResponse ingresarFacturaPorCotizacion(Inventario.ServiceReference1.ingresarFacturaPorCotizacionRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public Inventario.ServiceReference1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(Inventario.ServiceReference1.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public Inventario.ServiceReference1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(Inventario.ServiceReference1.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class escribirMemoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="escribirMemo", Namespace="http://tempuri.org/", Order=0)]
        public Inventario.ServiceReference1.escribirMemoRequestBody Body;
        
        public escribirMemoRequest() {
        }
        
        public escribirMemoRequest(Inventario.ServiceReference1.escribirMemoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class escribirMemoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string entrada;
        
        public escribirMemoRequestBody() {
        }
        
        public escribirMemoRequestBody(string usuario, string entrada) {
            this.usuario = usuario;
            this.entrada = entrada;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class escribirMemoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="escribirMemoResponse", Namespace="http://tempuri.org/", Order=0)]
        public Inventario.ServiceReference1.escribirMemoResponseBody Body;
        
        public escribirMemoResponse() {
        }
        
        public escribirMemoResponse(Inventario.ServiceReference1.escribirMemoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class escribirMemoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool escribirMemoResult;
        
        public escribirMemoResponseBody() {
        }
        
        public escribirMemoResponseBody(bool escribirMemoResult) {
            this.escribirMemoResult = escribirMemoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class obtenerMemosGenralesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="obtenerMemosGenrales", Namespace="http://tempuri.org/", Order=0)]
        public Inventario.ServiceReference1.obtenerMemosGenralesRequestBody Body;
        
        public obtenerMemosGenralesRequest() {
        }
        
        public obtenerMemosGenralesRequest(Inventario.ServiceReference1.obtenerMemosGenralesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class obtenerMemosGenralesRequestBody {
        
        public obtenerMemosGenralesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class obtenerMemosGenralesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="obtenerMemosGenralesResponse", Namespace="http://tempuri.org/", Order=0)]
        public Inventario.ServiceReference1.obtenerMemosGenralesResponseBody Body;
        
        public obtenerMemosGenralesResponse() {
        }
        
        public obtenerMemosGenralesResponse(Inventario.ServiceReference1.obtenerMemosGenralesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class obtenerMemosGenralesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement obtenerMemosGenralesResult;
        
        public obtenerMemosGenralesResponseBody() {
        }
        
        public obtenerMemosGenralesResponseBody(System.Xml.Linq.XElement obtenerMemosGenralesResult) {
            this.obtenerMemosGenralesResult = obtenerMemosGenralesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class guardarCotizacionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="guardarCotizacion", Namespace="http://tempuri.org/", Order=0)]
        public Inventario.ServiceReference1.guardarCotizacionRequestBody Body;
        
        public guardarCotizacionRequest() {
        }
        
        public guardarCotizacionRequest(Inventario.ServiceReference1.guardarCotizacionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class guardarCotizacionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement cotizacion;
        
        public guardarCotizacionRequestBody() {
        }
        
        public guardarCotizacionRequestBody(System.Xml.Linq.XElement cotizacion) {
            this.cotizacion = cotizacion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class guardarCotizacionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="guardarCotizacionResponse", Namespace="http://tempuri.org/", Order=0)]
        public Inventario.ServiceReference1.guardarCotizacionResponseBody Body;
        
        public guardarCotizacionResponse() {
        }
        
        public guardarCotizacionResponse(Inventario.ServiceReference1.guardarCotizacionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class guardarCotizacionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int guardarCotizacionResult;
        
        public guardarCotizacionResponseBody() {
        }
        
        public guardarCotizacionResponseBody(int guardarCotizacionResult) {
            this.guardarCotizacionResult = guardarCotizacionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class listaCotizacionesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="listaCotizaciones", Namespace="http://tempuri.org/", Order=0)]
        public Inventario.ServiceReference1.listaCotizacionesRequestBody Body;
        
        public listaCotizacionesRequest() {
        }
        
        public listaCotizacionesRequest(Inventario.ServiceReference1.listaCotizacionesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class listaCotizacionesRequestBody {
        
        public listaCotizacionesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class listaCotizacionesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="listaCotizacionesResponse", Namespace="http://tempuri.org/", Order=0)]
        public Inventario.ServiceReference1.listaCotizacionesResponseBody Body;
        
        public listaCotizacionesResponse() {
        }
        
        public listaCotizacionesResponse(Inventario.ServiceReference1.listaCotizacionesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class listaCotizacionesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement listaCotizacionesResult;
        
        public listaCotizacionesResponseBody() {
        }
        
        public listaCotizacionesResponseBody(System.Xml.Linq.XElement listaCotizacionesResult) {
            this.listaCotizacionesResult = listaCotizacionesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class obtenerFacturaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="obtenerFactura", Namespace="http://tempuri.org/", Order=0)]
        public Inventario.ServiceReference1.obtenerFacturaRequestBody Body;
        
        public obtenerFacturaRequest() {
        }
        
        public obtenerFacturaRequest(Inventario.ServiceReference1.obtenerFacturaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class obtenerFacturaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string vendedor;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string cliente;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string fecha;
        
        public obtenerFacturaRequestBody() {
        }
        
        public obtenerFacturaRequestBody(string vendedor, string cliente, string fecha) {
            this.vendedor = vendedor;
            this.cliente = cliente;
            this.fecha = fecha;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class obtenerFacturaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="obtenerFacturaResponse", Namespace="http://tempuri.org/", Order=0)]
        public Inventario.ServiceReference1.obtenerFacturaResponseBody Body;
        
        public obtenerFacturaResponse() {
        }
        
        public obtenerFacturaResponse(Inventario.ServiceReference1.obtenerFacturaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class obtenerFacturaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement obtenerFacturaResult;
        
        public obtenerFacturaResponseBody() {
        }
        
        public obtenerFacturaResponseBody(System.Xml.Linq.XElement obtenerFacturaResult) {
            this.obtenerFacturaResult = obtenerFacturaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class indicadoresEconomicosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="indicadoresEconomicos", Namespace="http://tempuri.org/", Order=0)]
        public Inventario.ServiceReference1.indicadoresEconomicosRequestBody Body;
        
        public indicadoresEconomicosRequest() {
        }
        
        public indicadoresEconomicosRequest(Inventario.ServiceReference1.indicadoresEconomicosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class indicadoresEconomicosRequestBody {
        
        public indicadoresEconomicosRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class indicadoresEconomicosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="indicadoresEconomicosResponse", Namespace="http://tempuri.org/", Order=0)]
        public Inventario.ServiceReference1.indicadoresEconomicosResponseBody Body;
        
        public indicadoresEconomicosResponse() {
        }
        
        public indicadoresEconomicosResponse(Inventario.ServiceReference1.indicadoresEconomicosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class indicadoresEconomicosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement indicadoresEconomicosResult;
        
        public indicadoresEconomicosResponseBody() {
        }
        
        public indicadoresEconomicosResponseBody(System.Xml.Linq.XElement indicadoresEconomicosResult) {
            this.indicadoresEconomicosResult = indicadoresEconomicosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class setearIndicadoresEconomicosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="setearIndicadoresEconomicos", Namespace="http://tempuri.org/", Order=0)]
        public Inventario.ServiceReference1.setearIndicadoresEconomicosRequestBody Body;
        
        public setearIndicadoresEconomicosRequest() {
        }
        
        public setearIndicadoresEconomicosRequest(Inventario.ServiceReference1.setearIndicadoresEconomicosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class setearIndicadoresEconomicosRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string dolar;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string euro;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string importe;
        
        public setearIndicadoresEconomicosRequestBody() {
        }
        
        public setearIndicadoresEconomicosRequestBody(string dolar, string euro, string importe) {
            this.dolar = dolar;
            this.euro = euro;
            this.importe = importe;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class setearIndicadoresEconomicosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="setearIndicadoresEconomicosResponse", Namespace="http://tempuri.org/", Order=0)]
        public Inventario.ServiceReference1.setearIndicadoresEconomicosResponseBody Body;
        
        public setearIndicadoresEconomicosResponse() {
        }
        
        public setearIndicadoresEconomicosResponse(Inventario.ServiceReference1.setearIndicadoresEconomicosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class setearIndicadoresEconomicosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool setearIndicadoresEconomicosResult;
        
        public setearIndicadoresEconomicosResponseBody() {
        }
        
        public setearIndicadoresEconomicosResponseBody(bool setearIndicadoresEconomicosResult) {
            this.setearIndicadoresEconomicosResult = setearIndicadoresEconomicosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ingresarFacturaLiberadaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ingresarFacturaLiberada", Namespace="http://tempuri.org/", Order=0)]
        public Inventario.ServiceReference1.ingresarFacturaLiberadaRequestBody Body;
        
        public ingresarFacturaLiberadaRequest() {
        }
        
        public ingresarFacturaLiberadaRequest(Inventario.ServiceReference1.ingresarFacturaLiberadaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ingresarFacturaLiberadaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement factura;
        
        public ingresarFacturaLiberadaRequestBody() {
        }
        
        public ingresarFacturaLiberadaRequestBody(System.Xml.Linq.XElement factura) {
            this.factura = factura;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ingresarFacturaLiberadaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ingresarFacturaLiberadaResponse", Namespace="http://tempuri.org/", Order=0)]
        public Inventario.ServiceReference1.ingresarFacturaLiberadaResponseBody Body;
        
        public ingresarFacturaLiberadaResponse() {
        }
        
        public ingresarFacturaLiberadaResponse(Inventario.ServiceReference1.ingresarFacturaLiberadaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ingresarFacturaLiberadaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ingresarFacturaLiberadaResult;
        
        public ingresarFacturaLiberadaResponseBody() {
        }
        
        public ingresarFacturaLiberadaResponseBody(bool ingresarFacturaLiberadaResult) {
            this.ingresarFacturaLiberadaResult = ingresarFacturaLiberadaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ingresarFacturaPorCotizacionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ingresarFacturaPorCotizacion", Namespace="http://tempuri.org/", Order=0)]
        public Inventario.ServiceReference1.ingresarFacturaPorCotizacionRequestBody Body;
        
        public ingresarFacturaPorCotizacionRequest() {
        }
        
        public ingresarFacturaPorCotizacionRequest(Inventario.ServiceReference1.ingresarFacturaPorCotizacionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ingresarFacturaPorCotizacionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fecha;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string vendedor;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string cliente;
        
        public ingresarFacturaPorCotizacionRequestBody() {
        }
        
        public ingresarFacturaPorCotizacionRequestBody(string fecha, string vendedor, string cliente) {
            this.fecha = fecha;
            this.vendedor = vendedor;
            this.cliente = cliente;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ingresarFacturaPorCotizacionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ingresarFacturaPorCotizacionResponse", Namespace="http://tempuri.org/", Order=0)]
        public Inventario.ServiceReference1.ingresarFacturaPorCotizacionResponseBody Body;
        
        public ingresarFacturaPorCotizacionResponse() {
        }
        
        public ingresarFacturaPorCotizacionResponse(Inventario.ServiceReference1.ingresarFacturaPorCotizacionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ingresarFacturaPorCotizacionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ingresarFacturaPorCotizacionResult;
        
        public ingresarFacturaPorCotizacionResponseBody() {
        }
        
        public ingresarFacturaPorCotizacionResponseBody(string ingresarFacturaPorCotizacionResult) {
            this.ingresarFacturaPorCotizacionResult = ingresarFacturaPorCotizacionResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : Inventario.ServiceReference1.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<Inventario.ServiceReference1.ServiceSoap>, Inventario.ServiceReference1.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Inventario.ServiceReference1.HelloWorldResponse Inventario.ServiceReference1.ServiceSoap.HelloWorld(Inventario.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            Inventario.ServiceReference1.HelloWorldRequest inValue = new Inventario.ServiceReference1.HelloWorldRequest();
            inValue.Body = new Inventario.ServiceReference1.HelloWorldRequestBody();
            Inventario.ServiceReference1.HelloWorldResponse retVal = ((Inventario.ServiceReference1.ServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Inventario.ServiceReference1.escribirMemoResponse Inventario.ServiceReference1.ServiceSoap.escribirMemo(Inventario.ServiceReference1.escribirMemoRequest request) {
            return base.Channel.escribirMemo(request);
        }
        
        public bool escribirMemo(string usuario, string entrada) {
            Inventario.ServiceReference1.escribirMemoRequest inValue = new Inventario.ServiceReference1.escribirMemoRequest();
            inValue.Body = new Inventario.ServiceReference1.escribirMemoRequestBody();
            inValue.Body.usuario = usuario;
            inValue.Body.entrada = entrada;
            Inventario.ServiceReference1.escribirMemoResponse retVal = ((Inventario.ServiceReference1.ServiceSoap)(this)).escribirMemo(inValue);
            return retVal.Body.escribirMemoResult;
        }
        
        public int estado() {
            return base.Channel.estado();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Inventario.ServiceReference1.obtenerMemosGenralesResponse Inventario.ServiceReference1.ServiceSoap.obtenerMemosGenrales(Inventario.ServiceReference1.obtenerMemosGenralesRequest request) {
            return base.Channel.obtenerMemosGenrales(request);
        }
        
        public System.Xml.Linq.XElement obtenerMemosGenrales() {
            Inventario.ServiceReference1.obtenerMemosGenralesRequest inValue = new Inventario.ServiceReference1.obtenerMemosGenralesRequest();
            inValue.Body = new Inventario.ServiceReference1.obtenerMemosGenralesRequestBody();
            Inventario.ServiceReference1.obtenerMemosGenralesResponse retVal = ((Inventario.ServiceReference1.ServiceSoap)(this)).obtenerMemosGenrales(inValue);
            return retVal.Body.obtenerMemosGenralesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Inventario.ServiceReference1.guardarCotizacionResponse Inventario.ServiceReference1.ServiceSoap.guardarCotizacion(Inventario.ServiceReference1.guardarCotizacionRequest request) {
            return base.Channel.guardarCotizacion(request);
        }
        
        public int guardarCotizacion(System.Xml.Linq.XElement cotizacion) {
            Inventario.ServiceReference1.guardarCotizacionRequest inValue = new Inventario.ServiceReference1.guardarCotizacionRequest();
            inValue.Body = new Inventario.ServiceReference1.guardarCotizacionRequestBody();
            inValue.Body.cotizacion = cotizacion;
            Inventario.ServiceReference1.guardarCotizacionResponse retVal = ((Inventario.ServiceReference1.ServiceSoap)(this)).guardarCotizacion(inValue);
            return retVal.Body.guardarCotizacionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Inventario.ServiceReference1.listaCotizacionesResponse Inventario.ServiceReference1.ServiceSoap.listaCotizaciones(Inventario.ServiceReference1.listaCotizacionesRequest request) {
            return base.Channel.listaCotizaciones(request);
        }
        
        public System.Xml.Linq.XElement listaCotizaciones() {
            Inventario.ServiceReference1.listaCotizacionesRequest inValue = new Inventario.ServiceReference1.listaCotizacionesRequest();
            inValue.Body = new Inventario.ServiceReference1.listaCotizacionesRequestBody();
            Inventario.ServiceReference1.listaCotizacionesResponse retVal = ((Inventario.ServiceReference1.ServiceSoap)(this)).listaCotizaciones(inValue);
            return retVal.Body.listaCotizacionesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Inventario.ServiceReference1.obtenerFacturaResponse Inventario.ServiceReference1.ServiceSoap.obtenerFactura(Inventario.ServiceReference1.obtenerFacturaRequest request) {
            return base.Channel.obtenerFactura(request);
        }
        
        public System.Xml.Linq.XElement obtenerFactura(string vendedor, string cliente, string fecha) {
            Inventario.ServiceReference1.obtenerFacturaRequest inValue = new Inventario.ServiceReference1.obtenerFacturaRequest();
            inValue.Body = new Inventario.ServiceReference1.obtenerFacturaRequestBody();
            inValue.Body.vendedor = vendedor;
            inValue.Body.cliente = cliente;
            inValue.Body.fecha = fecha;
            Inventario.ServiceReference1.obtenerFacturaResponse retVal = ((Inventario.ServiceReference1.ServiceSoap)(this)).obtenerFactura(inValue);
            return retVal.Body.obtenerFacturaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Inventario.ServiceReference1.indicadoresEconomicosResponse Inventario.ServiceReference1.ServiceSoap.indicadoresEconomicos(Inventario.ServiceReference1.indicadoresEconomicosRequest request) {
            return base.Channel.indicadoresEconomicos(request);
        }
        
        public System.Xml.Linq.XElement indicadoresEconomicos() {
            Inventario.ServiceReference1.indicadoresEconomicosRequest inValue = new Inventario.ServiceReference1.indicadoresEconomicosRequest();
            inValue.Body = new Inventario.ServiceReference1.indicadoresEconomicosRequestBody();
            Inventario.ServiceReference1.indicadoresEconomicosResponse retVal = ((Inventario.ServiceReference1.ServiceSoap)(this)).indicadoresEconomicos(inValue);
            return retVal.Body.indicadoresEconomicosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Inventario.ServiceReference1.setearIndicadoresEconomicosResponse Inventario.ServiceReference1.ServiceSoap.setearIndicadoresEconomicos(Inventario.ServiceReference1.setearIndicadoresEconomicosRequest request) {
            return base.Channel.setearIndicadoresEconomicos(request);
        }
        
        public bool setearIndicadoresEconomicos(string dolar, string euro, string importe) {
            Inventario.ServiceReference1.setearIndicadoresEconomicosRequest inValue = new Inventario.ServiceReference1.setearIndicadoresEconomicosRequest();
            inValue.Body = new Inventario.ServiceReference1.setearIndicadoresEconomicosRequestBody();
            inValue.Body.dolar = dolar;
            inValue.Body.euro = euro;
            inValue.Body.importe = importe;
            Inventario.ServiceReference1.setearIndicadoresEconomicosResponse retVal = ((Inventario.ServiceReference1.ServiceSoap)(this)).setearIndicadoresEconomicos(inValue);
            return retVal.Body.setearIndicadoresEconomicosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Inventario.ServiceReference1.ingresarFacturaLiberadaResponse Inventario.ServiceReference1.ServiceSoap.ingresarFacturaLiberada(Inventario.ServiceReference1.ingresarFacturaLiberadaRequest request) {
            return base.Channel.ingresarFacturaLiberada(request);
        }
        
        public bool ingresarFacturaLiberada(System.Xml.Linq.XElement factura) {
            Inventario.ServiceReference1.ingresarFacturaLiberadaRequest inValue = new Inventario.ServiceReference1.ingresarFacturaLiberadaRequest();
            inValue.Body = new Inventario.ServiceReference1.ingresarFacturaLiberadaRequestBody();
            inValue.Body.factura = factura;
            Inventario.ServiceReference1.ingresarFacturaLiberadaResponse retVal = ((Inventario.ServiceReference1.ServiceSoap)(this)).ingresarFacturaLiberada(inValue);
            return retVal.Body.ingresarFacturaLiberadaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Inventario.ServiceReference1.ingresarFacturaPorCotizacionResponse Inventario.ServiceReference1.ServiceSoap.ingresarFacturaPorCotizacion(Inventario.ServiceReference1.ingresarFacturaPorCotizacionRequest request) {
            return base.Channel.ingresarFacturaPorCotizacion(request);
        }
        
        public string ingresarFacturaPorCotizacion(string fecha, string vendedor, string cliente) {
            Inventario.ServiceReference1.ingresarFacturaPorCotizacionRequest inValue = new Inventario.ServiceReference1.ingresarFacturaPorCotizacionRequest();
            inValue.Body = new Inventario.ServiceReference1.ingresarFacturaPorCotizacionRequestBody();
            inValue.Body.fecha = fecha;
            inValue.Body.vendedor = vendedor;
            inValue.Body.cliente = cliente;
            Inventario.ServiceReference1.ingresarFacturaPorCotizacionResponse retVal = ((Inventario.ServiceReference1.ServiceSoap)(this)).ingresarFacturaPorCotizacion(inValue);
            return retVal.Body.ingresarFacturaPorCotizacionResult;
        }
    }
}
