//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18408
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventario.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ServiceSoap")]
    public interface ServiceSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento HelloWorldResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        Inventario.ServiceReference1.HelloWorldResponse HelloWorld(Inventario.ServiceReference1.HelloWorldRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento usuario del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/escribirMemo", ReplyAction="*")]
        Inventario.ServiceReference1.escribirMemoResponse escribirMemo(Inventario.ServiceReference1.escribirMemoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/estado", ReplyAction="*")]
        int estado();
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento obtenerMemosGenralesResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/obtenerMemosGenrales", ReplyAction="*")]
        Inventario.ServiceReference1.obtenerMemosGenralesResponse obtenerMemosGenrales(Inventario.ServiceReference1.obtenerMemosGenralesRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento cotizacion del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/guardarCotizacion", ReplyAction="*")]
        Inventario.ServiceReference1.guardarCotizacionResponse guardarCotizacion(Inventario.ServiceReference1.guardarCotizacionRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento listaCotizacionesResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/listaCotizaciones", ReplyAction="*")]
        Inventario.ServiceReference1.listaCotizacionesResponse listaCotizaciones(Inventario.ServiceReference1.listaCotizacionesRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento obtenerFacturaResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/obtenerFactura", ReplyAction="*")]
        Inventario.ServiceReference1.obtenerFacturaResponse obtenerFactura(Inventario.ServiceReference1.obtenerFacturaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento indicadoresEconomicosResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/indicadoresEconomicos", ReplyAction="*")]
        Inventario.ServiceReference1.indicadoresEconomicosResponse indicadoresEconomicos(Inventario.ServiceReference1.indicadoresEconomicosRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento dolar del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/setearIndicadoresEconomicos", ReplyAction="*")]
        Inventario.ServiceReference1.setearIndicadoresEconomicosResponse setearIndicadoresEconomicos(Inventario.ServiceReference1.setearIndicadoresEconomicosRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento factura del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ingresarFacturaLiberada", ReplyAction="*")]
        Inventario.ServiceReference1.ingresarFacturaLiberadaResponse ingresarFacturaLiberada(Inventario.ServiceReference1.ingresarFacturaLiberadaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ingresarFacturaPorCotizacionResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ingresarFacturaPorCotizacion", ReplyAction="*")]
        Inventario.ServiceReference1.ingresarFacturaPorCotizacionResponse ingresarFacturaPorCotizacion(Inventario.ServiceReference1.ingresarFacturaPorCotizacionRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento facturasResumenResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/facturasResumen", ReplyAction="*")]
        Inventario.ServiceReference1.facturasResumenResponse facturasResumen(Inventario.ServiceReference1.facturasResumenRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento consultarActualizacionResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/consultarActualizacion", ReplyAction="*")]
        Inventario.ServiceReference1.consultarActualizacionResponse consultarActualizacion(Inventario.ServiceReference1.consultarActualizacionRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento version del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/subirActualizacionAServidor", ReplyAction="*")]
        Inventario.ServiceReference1.subirActualizacionAServidorResponse subirActualizacionAServidor(Inventario.ServiceReference1.subirActualizacionAServidorRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento factura del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IngresarFacturaIngreso", ReplyAction="*")]
        Inventario.ServiceReference1.IngresarFacturaIngresoResponse IngresarFacturaIngreso(Inventario.ServiceReference1.IngresarFacturaIngresoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento facturasIngresoResumenResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/facturasIngresoResumen", ReplyAction="*")]
        Inventario.ServiceReference1.facturasIngresoResumenResponse facturasIngresoResumen(Inventario.ServiceReference1.facturasIngresoResumenRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento NP del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ingresoPMP", ReplyAction="*")]
        Inventario.ServiceReference1.ingresoPMPResponse ingresoPMP(Inventario.ServiceReference1.ingresoPMPRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento obtenerPMPResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/obtenerPMP", ReplyAction="*")]
        Inventario.ServiceReference1.obtenerPMPResponse obtenerPMP(Inventario.ServiceReference1.obtenerPMPRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento name del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/uploadFile", ReplyAction="*")]
        Inventario.ServiceReference1.uploadFileResponse uploadFile(Inventario.ServiceReference1.uploadFileRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public Inventario.ServiceReference1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(Inventario.ServiceReference1.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public Inventario.ServiceReference1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(Inventario.ServiceReference1.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class escribirMemoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="escribirMemo", Namespace="http://tempuri.org/", Order=0)]
        public Inventario.ServiceReference1.escribirMemoRequestBody Body;
        
        public escribirMemoRequest() {
        }
        
        public escribirMemoRequest(Inventario.ServiceReference1.escribirMemoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class escribirMemoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string entrada;
        
        public escribirMemoRequestBody() {
        }
        
        public escribirMemoRequestBody(string usuario, string entrada) {
            this.usuario = usuario;
            this.entrada = entrada;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class escribirMemoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="escribirMemoResponse", Namespace="http://tempuri.org/", Order=0)]
        public Inventario.ServiceReference1.escribirMemoResponseBody Body;
        
        public escribirMemoResponse() {
        }
        
        public escribirMemoResponse(Inventario.ServiceReference1.escribirMemoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class escribirMemoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool escribirMemoResult;
        
        public escribirMemoResponseBody() {
        }
        
        public escribirMemoResponseBody(bool escribirMemoResult) {
            this.escribirMemoResult = escribirMemoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class obtenerMemosGenralesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="obtenerMemosGenrales", Namespace="http://tempuri.org/", Order=0)]
        public Inventario.ServiceReference1.obtenerMemosGenralesRequestBody Body;
        
        public obtenerMemosGenralesRequest() {
        }
        
        public obtenerMemosGenralesRequest(Inventario.ServiceReference1.obtenerMemosGenralesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class obtenerMemosGenralesRequestBody {
        
        public obtenerMemosGenralesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class obtenerMemosGenralesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="obtenerMemosGenralesResponse", Namespace="http://tempuri.org/", Order=0)]
        public Inventario.ServiceReference1.obtenerMemosGenralesResponseBody Body;
        
        public obtenerMemosGenralesResponse() {
        }
        
        public obtenerMemosGenralesResponse(Inventario.ServiceReference1.obtenerMemosGenralesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class obtenerMemosGenralesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement obtenerMemosGenralesResult;
        
        public obtenerMemosGenralesResponseBody() {
        }
        
        public obtenerMemosGenralesResponseBody(System.Xml.Linq.XElement obtenerMemosGenralesResult) {
            this.obtenerMemosGenralesResult = obtenerMemosGenralesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class guardarCotizacionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="guardarCotizacion", Namespace="http://tempuri.org/", Order=0)]
        public Inventario.ServiceReference1.guardarCotizacionRequestBody Body;
        
        public guardarCotizacionRequest() {
        }
        
        public guardarCotizacionRequest(Inventario.ServiceReference1.guardarCotizacionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class guardarCotizacionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement cotizacion;
        
        public guardarCotizacionRequestBody() {
        }
        
        public guardarCotizacionRequestBody(System.Xml.Linq.XElement cotizacion) {
            this.cotizacion = cotizacion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class guardarCotizacionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="guardarCotizacionResponse", Namespace="http://tempuri.org/", Order=0)]
        public Inventario.ServiceReference1.guardarCotizacionResponseBody Body;
        
        public guardarCotizacionResponse() {
        }
        
        public guardarCotizacionResponse(Inventario.ServiceReference1.guardarCotizacionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class guardarCotizacionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int guardarCotizacionResult;
        
        public guardarCotizacionResponseBody() {
        }
        
        public guardarCotizacionResponseBody(int guardarCotizacionResult) {
            this.guardarCotizacionResult = guardarCotizacionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class listaCotizacionesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="listaCotizaciones", Namespace="http://tempuri.org/", Order=0)]
        public Inventario.ServiceReference1.listaCotizacionesRequestBody Body;
        
        public listaCotizacionesRequest() {
        }
        
        public listaCotizacionesRequest(Inventario.ServiceReference1.listaCotizacionesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class listaCotizacionesRequestBody {
        
        public listaCotizacionesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class listaCotizacionesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="listaCotizacionesResponse", Namespace="http://tempuri.org/", Order=0)]
        public Inventario.ServiceReference1.listaCotizacionesResponseBody Body;
        
        public listaCotizacionesResponse() {
        }
        
        public listaCotizacionesResponse(Inventario.ServiceReference1.listaCotizacionesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class listaCotizacionesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement listaCotizacionesResult;
        
        public listaCotizacionesResponseBody() {
        }
        
        public listaCotizacionesResponseBody(System.Xml.Linq.XElement listaCotizacionesResult) {
            this.listaCotizacionesResult = listaCotizacionesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class obtenerFacturaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="obtenerFactura", Namespace="http://tempuri.org/", Order=0)]
        public Inventario.ServiceReference1.obtenerFacturaRequestBody Body;
        
        public obtenerFacturaRequest() {
        }
        
        public obtenerFacturaRequest(Inventario.ServiceReference1.obtenerFacturaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class obtenerFacturaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int numero;
        
        public obtenerFacturaRequestBody() {
        }
        
        public obtenerFacturaRequestBody(int numero) {
            this.numero = numero;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class obtenerFacturaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="obtenerFacturaResponse", Namespace="http://tempuri.org/", Order=0)]
        public Inventario.ServiceReference1.obtenerFacturaResponseBody Body;
        
        public obtenerFacturaResponse() {
        }
        
        public obtenerFacturaResponse(Inventario.ServiceReference1.obtenerFacturaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class obtenerFacturaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement obtenerFacturaResult;
        
        public obtenerFacturaResponseBody() {
        }
        
        public obtenerFacturaResponseBody(System.Xml.Linq.XElement obtenerFacturaResult) {
            this.obtenerFacturaResult = obtenerFacturaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class indicadoresEconomicosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="indicadoresEconomicos", Namespace="http://tempuri.org/", Order=0)]
        public Inventario.ServiceReference1.indicadoresEconomicosRequestBody Body;
        
        public indicadoresEconomicosRequest() {
        }
        
        public indicadoresEconomicosRequest(Inventario.ServiceReference1.indicadoresEconomicosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class indicadoresEconomicosRequestBody {
        
        public indicadoresEconomicosRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class indicadoresEconomicosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="indicadoresEconomicosResponse", Namespace="http://tempuri.org/", Order=0)]
        public Inventario.ServiceReference1.indicadoresEconomicosResponseBody Body;
        
        public indicadoresEconomicosResponse() {
        }
        
        public indicadoresEconomicosResponse(Inventario.ServiceReference1.indicadoresEconomicosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class indicadoresEconomicosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement indicadoresEconomicosResult;
        
        public indicadoresEconomicosResponseBody() {
        }
        
        public indicadoresEconomicosResponseBody(System.Xml.Linq.XElement indicadoresEconomicosResult) {
            this.indicadoresEconomicosResult = indicadoresEconomicosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class setearIndicadoresEconomicosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="setearIndicadoresEconomicos", Namespace="http://tempuri.org/", Order=0)]
        public Inventario.ServiceReference1.setearIndicadoresEconomicosRequestBody Body;
        
        public setearIndicadoresEconomicosRequest() {
        }
        
        public setearIndicadoresEconomicosRequest(Inventario.ServiceReference1.setearIndicadoresEconomicosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class setearIndicadoresEconomicosRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string dolar;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string euro;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string importe;
        
        public setearIndicadoresEconomicosRequestBody() {
        }
        
        public setearIndicadoresEconomicosRequestBody(string dolar, string euro, string importe) {
            this.dolar = dolar;
            this.euro = euro;
            this.importe = importe;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class setearIndicadoresEconomicosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="setearIndicadoresEconomicosResponse", Namespace="http://tempuri.org/", Order=0)]
        public Inventario.ServiceReference1.setearIndicadoresEconomicosResponseBody Body;
        
        public setearIndicadoresEconomicosResponse() {
        }
        
        public setearIndicadoresEconomicosResponse(Inventario.ServiceReference1.setearIndicadoresEconomicosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class setearIndicadoresEconomicosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool setearIndicadoresEconomicosResult;
        
        public setearIndicadoresEconomicosResponseBody() {
        }
        
        public setearIndicadoresEconomicosResponseBody(bool setearIndicadoresEconomicosResult) {
            this.setearIndicadoresEconomicosResult = setearIndicadoresEconomicosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ingresarFacturaLiberadaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ingresarFacturaLiberada", Namespace="http://tempuri.org/", Order=0)]
        public Inventario.ServiceReference1.ingresarFacturaLiberadaRequestBody Body;
        
        public ingresarFacturaLiberadaRequest() {
        }
        
        public ingresarFacturaLiberadaRequest(Inventario.ServiceReference1.ingresarFacturaLiberadaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ingresarFacturaLiberadaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement factura;
        
        public ingresarFacturaLiberadaRequestBody() {
        }
        
        public ingresarFacturaLiberadaRequestBody(System.Xml.Linq.XElement factura) {
            this.factura = factura;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ingresarFacturaLiberadaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ingresarFacturaLiberadaResponse", Namespace="http://tempuri.org/", Order=0)]
        public Inventario.ServiceReference1.ingresarFacturaLiberadaResponseBody Body;
        
        public ingresarFacturaLiberadaResponse() {
        }
        
        public ingresarFacturaLiberadaResponse(Inventario.ServiceReference1.ingresarFacturaLiberadaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ingresarFacturaLiberadaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ingresarFacturaLiberadaResult;
        
        public ingresarFacturaLiberadaResponseBody() {
        }
        
        public ingresarFacturaLiberadaResponseBody(bool ingresarFacturaLiberadaResult) {
            this.ingresarFacturaLiberadaResult = ingresarFacturaLiberadaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ingresarFacturaPorCotizacionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ingresarFacturaPorCotizacion", Namespace="http://tempuri.org/", Order=0)]
        public Inventario.ServiceReference1.ingresarFacturaPorCotizacionRequestBody Body;
        
        public ingresarFacturaPorCotizacionRequest() {
        }
        
        public ingresarFacturaPorCotizacionRequest(Inventario.ServiceReference1.ingresarFacturaPorCotizacionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ingresarFacturaPorCotizacionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int identificacion;
        
        public ingresarFacturaPorCotizacionRequestBody() {
        }
        
        public ingresarFacturaPorCotizacionRequestBody(int identificacion) {
            this.identificacion = identificacion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ingresarFacturaPorCotizacionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ingresarFacturaPorCotizacionResponse", Namespace="http://tempuri.org/", Order=0)]
        public Inventario.ServiceReference1.ingresarFacturaPorCotizacionResponseBody Body;
        
        public ingresarFacturaPorCotizacionResponse() {
        }
        
        public ingresarFacturaPorCotizacionResponse(Inventario.ServiceReference1.ingresarFacturaPorCotizacionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ingresarFacturaPorCotizacionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ingresarFacturaPorCotizacionResult;
        
        public ingresarFacturaPorCotizacionResponseBody() {
        }
        
        public ingresarFacturaPorCotizacionResponseBody(string ingresarFacturaPorCotizacionResult) {
            this.ingresarFacturaPorCotizacionResult = ingresarFacturaPorCotizacionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class facturasResumenRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="facturasResumen", Namespace="http://tempuri.org/", Order=0)]
        public Inventario.ServiceReference1.facturasResumenRequestBody Body;
        
        public facturasResumenRequest() {
        }
        
        public facturasResumenRequest(Inventario.ServiceReference1.facturasResumenRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class facturasResumenRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int año;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int mes;
        
        public facturasResumenRequestBody() {
        }
        
        public facturasResumenRequestBody(int año, int mes) {
            this.año = año;
            this.mes = mes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class facturasResumenResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="facturasResumenResponse", Namespace="http://tempuri.org/", Order=0)]
        public Inventario.ServiceReference1.facturasResumenResponseBody Body;
        
        public facturasResumenResponse() {
        }
        
        public facturasResumenResponse(Inventario.ServiceReference1.facturasResumenResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class facturasResumenResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement facturasResumenResult;
        
        public facturasResumenResponseBody() {
        }
        
        public facturasResumenResponseBody(System.Xml.Linq.XElement facturasResumenResult) {
            this.facturasResumenResult = facturasResumenResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultarActualizacionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="consultarActualizacion", Namespace="http://tempuri.org/", Order=0)]
        public Inventario.ServiceReference1.consultarActualizacionRequestBody Body;
        
        public consultarActualizacionRequest() {
        }
        
        public consultarActualizacionRequest(Inventario.ServiceReference1.consultarActualizacionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class consultarActualizacionRequestBody {
        
        public consultarActualizacionRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultarActualizacionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="consultarActualizacionResponse", Namespace="http://tempuri.org/", Order=0)]
        public Inventario.ServiceReference1.consultarActualizacionResponseBody Body;
        
        public consultarActualizacionResponse() {
        }
        
        public consultarActualizacionResponse(Inventario.ServiceReference1.consultarActualizacionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class consultarActualizacionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string consultarActualizacionResult;
        
        public consultarActualizacionResponseBody() {
        }
        
        public consultarActualizacionResponseBody(string consultarActualizacionResult) {
            this.consultarActualizacionResult = consultarActualizacionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class subirActualizacionAServidorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="subirActualizacionAServidor", Namespace="http://tempuri.org/", Order=0)]
        public Inventario.ServiceReference1.subirActualizacionAServidorRequestBody Body;
        
        public subirActualizacionAServidorRequest() {
        }
        
        public subirActualizacionAServidorRequest(Inventario.ServiceReference1.subirActualizacionAServidorRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class subirActualizacionAServidorRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string version;
        
        public subirActualizacionAServidorRequestBody() {
        }
        
        public subirActualizacionAServidorRequestBody(string version) {
            this.version = version;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class subirActualizacionAServidorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="subirActualizacionAServidorResponse", Namespace="http://tempuri.org/", Order=0)]
        public Inventario.ServiceReference1.subirActualizacionAServidorResponseBody Body;
        
        public subirActualizacionAServidorResponse() {
        }
        
        public subirActualizacionAServidorResponse(Inventario.ServiceReference1.subirActualizacionAServidorResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class subirActualizacionAServidorResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool subirActualizacionAServidorResult;
        
        public subirActualizacionAServidorResponseBody() {
        }
        
        public subirActualizacionAServidorResponseBody(bool subirActualizacionAServidorResult) {
            this.subirActualizacionAServidorResult = subirActualizacionAServidorResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IngresarFacturaIngresoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IngresarFacturaIngreso", Namespace="http://tempuri.org/", Order=0)]
        public Inventario.ServiceReference1.IngresarFacturaIngresoRequestBody Body;
        
        public IngresarFacturaIngresoRequest() {
        }
        
        public IngresarFacturaIngresoRequest(Inventario.ServiceReference1.IngresarFacturaIngresoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class IngresarFacturaIngresoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement factura;
        
        public IngresarFacturaIngresoRequestBody() {
        }
        
        public IngresarFacturaIngresoRequestBody(System.Xml.Linq.XElement factura) {
            this.factura = factura;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IngresarFacturaIngresoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IngresarFacturaIngresoResponse", Namespace="http://tempuri.org/", Order=0)]
        public Inventario.ServiceReference1.IngresarFacturaIngresoResponseBody Body;
        
        public IngresarFacturaIngresoResponse() {
        }
        
        public IngresarFacturaIngresoResponse(Inventario.ServiceReference1.IngresarFacturaIngresoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class IngresarFacturaIngresoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool IngresarFacturaIngresoResult;
        
        public IngresarFacturaIngresoResponseBody() {
        }
        
        public IngresarFacturaIngresoResponseBody(bool IngresarFacturaIngresoResult) {
            this.IngresarFacturaIngresoResult = IngresarFacturaIngresoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class facturasIngresoResumenRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="facturasIngresoResumen", Namespace="http://tempuri.org/", Order=0)]
        public Inventario.ServiceReference1.facturasIngresoResumenRequestBody Body;
        
        public facturasIngresoResumenRequest() {
        }
        
        public facturasIngresoResumenRequest(Inventario.ServiceReference1.facturasIngresoResumenRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class facturasIngresoResumenRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int año;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int mes;
        
        public facturasIngresoResumenRequestBody() {
        }
        
        public facturasIngresoResumenRequestBody(int año, int mes) {
            this.año = año;
            this.mes = mes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class facturasIngresoResumenResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="facturasIngresoResumenResponse", Namespace="http://tempuri.org/", Order=0)]
        public Inventario.ServiceReference1.facturasIngresoResumenResponseBody Body;
        
        public facturasIngresoResumenResponse() {
        }
        
        public facturasIngresoResumenResponse(Inventario.ServiceReference1.facturasIngresoResumenResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class facturasIngresoResumenResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement facturasIngresoResumenResult;
        
        public facturasIngresoResumenResponseBody() {
        }
        
        public facturasIngresoResumenResponseBody(System.Xml.Linq.XElement facturasIngresoResumenResult) {
            this.facturasIngresoResumenResult = facturasIngresoResumenResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ingresoPMPRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ingresoPMP", Namespace="http://tempuri.org/", Order=0)]
        public Inventario.ServiceReference1.ingresoPMPRequestBody Body;
        
        public ingresoPMPRequest() {
        }
        
        public ingresoPMPRequest(Inventario.ServiceReference1.ingresoPMPRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ingresoPMPRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string NP;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int NoE;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int EoS;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int cantidad;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int precioFTR;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int precioEXP;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string moneda;
        
        public ingresoPMPRequestBody() {
        }
        
        public ingresoPMPRequestBody(string NP, int NoE, int EoS, int cantidad, int precioFTR, int precioEXP, string moneda) {
            this.NP = NP;
            this.NoE = NoE;
            this.EoS = EoS;
            this.cantidad = cantidad;
            this.precioFTR = precioFTR;
            this.precioEXP = precioEXP;
            this.moneda = moneda;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ingresoPMPResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ingresoPMPResponse", Namespace="http://tempuri.org/", Order=0)]
        public Inventario.ServiceReference1.ingresoPMPResponseBody Body;
        
        public ingresoPMPResponse() {
        }
        
        public ingresoPMPResponse(Inventario.ServiceReference1.ingresoPMPResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ingresoPMPResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ingresoPMPResult;
        
        public ingresoPMPResponseBody() {
        }
        
        public ingresoPMPResponseBody(bool ingresoPMPResult) {
            this.ingresoPMPResult = ingresoPMPResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class obtenerPMPRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="obtenerPMP", Namespace="http://tempuri.org/", Order=0)]
        public Inventario.ServiceReference1.obtenerPMPRequestBody Body;
        
        public obtenerPMPRequest() {
        }
        
        public obtenerPMPRequest(Inventario.ServiceReference1.obtenerPMPRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class obtenerPMPRequestBody {
        
        public obtenerPMPRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class obtenerPMPResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="obtenerPMPResponse", Namespace="http://tempuri.org/", Order=0)]
        public Inventario.ServiceReference1.obtenerPMPResponseBody Body;
        
        public obtenerPMPResponse() {
        }
        
        public obtenerPMPResponse(Inventario.ServiceReference1.obtenerPMPResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class obtenerPMPResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement obtenerPMPResult;
        
        public obtenerPMPResponseBody() {
        }
        
        public obtenerPMPResponseBody(System.Xml.Linq.XElement obtenerPMPResult) {
            this.obtenerPMPResult = obtenerPMPResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class uploadFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="uploadFile", Namespace="http://tempuri.org/", Order=0)]
        public Inventario.ServiceReference1.uploadFileRequestBody Body;
        
        public uploadFileRequest() {
        }
        
        public uploadFileRequest(Inventario.ServiceReference1.uploadFileRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class uploadFileRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        public uploadFileRequestBody() {
        }
        
        public uploadFileRequestBody(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class uploadFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="uploadFileResponse", Namespace="http://tempuri.org/", Order=0)]
        public Inventario.ServiceReference1.uploadFileResponseBody Body;
        
        public uploadFileResponse() {
        }
        
        public uploadFileResponse(Inventario.ServiceReference1.uploadFileResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class uploadFileResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool uploadFileResult;
        
        public uploadFileResponseBody() {
        }
        
        public uploadFileResponseBody(bool uploadFileResult) {
            this.uploadFileResult = uploadFileResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : Inventario.ServiceReference1.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<Inventario.ServiceReference1.ServiceSoap>, Inventario.ServiceReference1.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Inventario.ServiceReference1.HelloWorldResponse Inventario.ServiceReference1.ServiceSoap.HelloWorld(Inventario.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            Inventario.ServiceReference1.HelloWorldRequest inValue = new Inventario.ServiceReference1.HelloWorldRequest();
            inValue.Body = new Inventario.ServiceReference1.HelloWorldRequestBody();
            Inventario.ServiceReference1.HelloWorldResponse retVal = ((Inventario.ServiceReference1.ServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Inventario.ServiceReference1.escribirMemoResponse Inventario.ServiceReference1.ServiceSoap.escribirMemo(Inventario.ServiceReference1.escribirMemoRequest request) {
            return base.Channel.escribirMemo(request);
        }
        
        public bool escribirMemo(string usuario, string entrada) {
            Inventario.ServiceReference1.escribirMemoRequest inValue = new Inventario.ServiceReference1.escribirMemoRequest();
            inValue.Body = new Inventario.ServiceReference1.escribirMemoRequestBody();
            inValue.Body.usuario = usuario;
            inValue.Body.entrada = entrada;
            Inventario.ServiceReference1.escribirMemoResponse retVal = ((Inventario.ServiceReference1.ServiceSoap)(this)).escribirMemo(inValue);
            return retVal.Body.escribirMemoResult;
        }
        
        public int estado() {
            return base.Channel.estado();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Inventario.ServiceReference1.obtenerMemosGenralesResponse Inventario.ServiceReference1.ServiceSoap.obtenerMemosGenrales(Inventario.ServiceReference1.obtenerMemosGenralesRequest request) {
            return base.Channel.obtenerMemosGenrales(request);
        }
        
        public System.Xml.Linq.XElement obtenerMemosGenrales() {
            Inventario.ServiceReference1.obtenerMemosGenralesRequest inValue = new Inventario.ServiceReference1.obtenerMemosGenralesRequest();
            inValue.Body = new Inventario.ServiceReference1.obtenerMemosGenralesRequestBody();
            Inventario.ServiceReference1.obtenerMemosGenralesResponse retVal = ((Inventario.ServiceReference1.ServiceSoap)(this)).obtenerMemosGenrales(inValue);
            return retVal.Body.obtenerMemosGenralesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Inventario.ServiceReference1.guardarCotizacionResponse Inventario.ServiceReference1.ServiceSoap.guardarCotizacion(Inventario.ServiceReference1.guardarCotizacionRequest request) {
            return base.Channel.guardarCotizacion(request);
        }
        
        public int guardarCotizacion(System.Xml.Linq.XElement cotizacion) {
            Inventario.ServiceReference1.guardarCotizacionRequest inValue = new Inventario.ServiceReference1.guardarCotizacionRequest();
            inValue.Body = new Inventario.ServiceReference1.guardarCotizacionRequestBody();
            inValue.Body.cotizacion = cotizacion;
            Inventario.ServiceReference1.guardarCotizacionResponse retVal = ((Inventario.ServiceReference1.ServiceSoap)(this)).guardarCotizacion(inValue);
            return retVal.Body.guardarCotizacionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Inventario.ServiceReference1.listaCotizacionesResponse Inventario.ServiceReference1.ServiceSoap.listaCotizaciones(Inventario.ServiceReference1.listaCotizacionesRequest request) {
            return base.Channel.listaCotizaciones(request);
        }
        
        public System.Xml.Linq.XElement listaCotizaciones() {
            Inventario.ServiceReference1.listaCotizacionesRequest inValue = new Inventario.ServiceReference1.listaCotizacionesRequest();
            inValue.Body = new Inventario.ServiceReference1.listaCotizacionesRequestBody();
            Inventario.ServiceReference1.listaCotizacionesResponse retVal = ((Inventario.ServiceReference1.ServiceSoap)(this)).listaCotizaciones(inValue);
            return retVal.Body.listaCotizacionesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Inventario.ServiceReference1.obtenerFacturaResponse Inventario.ServiceReference1.ServiceSoap.obtenerFactura(Inventario.ServiceReference1.obtenerFacturaRequest request) {
            return base.Channel.obtenerFactura(request);
        }
        
        public System.Xml.Linq.XElement obtenerFactura(int numero) {
            Inventario.ServiceReference1.obtenerFacturaRequest inValue = new Inventario.ServiceReference1.obtenerFacturaRequest();
            inValue.Body = new Inventario.ServiceReference1.obtenerFacturaRequestBody();
            inValue.Body.numero = numero;
            Inventario.ServiceReference1.obtenerFacturaResponse retVal = ((Inventario.ServiceReference1.ServiceSoap)(this)).obtenerFactura(inValue);
            return retVal.Body.obtenerFacturaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Inventario.ServiceReference1.indicadoresEconomicosResponse Inventario.ServiceReference1.ServiceSoap.indicadoresEconomicos(Inventario.ServiceReference1.indicadoresEconomicosRequest request) {
            return base.Channel.indicadoresEconomicos(request);
        }
        
        public System.Xml.Linq.XElement indicadoresEconomicos() {
            Inventario.ServiceReference1.indicadoresEconomicosRequest inValue = new Inventario.ServiceReference1.indicadoresEconomicosRequest();
            inValue.Body = new Inventario.ServiceReference1.indicadoresEconomicosRequestBody();
            Inventario.ServiceReference1.indicadoresEconomicosResponse retVal = ((Inventario.ServiceReference1.ServiceSoap)(this)).indicadoresEconomicos(inValue);
            return retVal.Body.indicadoresEconomicosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Inventario.ServiceReference1.setearIndicadoresEconomicosResponse Inventario.ServiceReference1.ServiceSoap.setearIndicadoresEconomicos(Inventario.ServiceReference1.setearIndicadoresEconomicosRequest request) {
            return base.Channel.setearIndicadoresEconomicos(request);
        }
        
        public bool setearIndicadoresEconomicos(string dolar, string euro, string importe) {
            Inventario.ServiceReference1.setearIndicadoresEconomicosRequest inValue = new Inventario.ServiceReference1.setearIndicadoresEconomicosRequest();
            inValue.Body = new Inventario.ServiceReference1.setearIndicadoresEconomicosRequestBody();
            inValue.Body.dolar = dolar;
            inValue.Body.euro = euro;
            inValue.Body.importe = importe;
            Inventario.ServiceReference1.setearIndicadoresEconomicosResponse retVal = ((Inventario.ServiceReference1.ServiceSoap)(this)).setearIndicadoresEconomicos(inValue);
            return retVal.Body.setearIndicadoresEconomicosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Inventario.ServiceReference1.ingresarFacturaLiberadaResponse Inventario.ServiceReference1.ServiceSoap.ingresarFacturaLiberada(Inventario.ServiceReference1.ingresarFacturaLiberadaRequest request) {
            return base.Channel.ingresarFacturaLiberada(request);
        }
        
        public bool ingresarFacturaLiberada(System.Xml.Linq.XElement factura) {
            Inventario.ServiceReference1.ingresarFacturaLiberadaRequest inValue = new Inventario.ServiceReference1.ingresarFacturaLiberadaRequest();
            inValue.Body = new Inventario.ServiceReference1.ingresarFacturaLiberadaRequestBody();
            inValue.Body.factura = factura;
            Inventario.ServiceReference1.ingresarFacturaLiberadaResponse retVal = ((Inventario.ServiceReference1.ServiceSoap)(this)).ingresarFacturaLiberada(inValue);
            return retVal.Body.ingresarFacturaLiberadaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Inventario.ServiceReference1.ingresarFacturaPorCotizacionResponse Inventario.ServiceReference1.ServiceSoap.ingresarFacturaPorCotizacion(Inventario.ServiceReference1.ingresarFacturaPorCotizacionRequest request) {
            return base.Channel.ingresarFacturaPorCotizacion(request);
        }
        
        public string ingresarFacturaPorCotizacion(int identificacion) {
            Inventario.ServiceReference1.ingresarFacturaPorCotizacionRequest inValue = new Inventario.ServiceReference1.ingresarFacturaPorCotizacionRequest();
            inValue.Body = new Inventario.ServiceReference1.ingresarFacturaPorCotizacionRequestBody();
            inValue.Body.identificacion = identificacion;
            Inventario.ServiceReference1.ingresarFacturaPorCotizacionResponse retVal = ((Inventario.ServiceReference1.ServiceSoap)(this)).ingresarFacturaPorCotizacion(inValue);
            return retVal.Body.ingresarFacturaPorCotizacionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Inventario.ServiceReference1.facturasResumenResponse Inventario.ServiceReference1.ServiceSoap.facturasResumen(Inventario.ServiceReference1.facturasResumenRequest request) {
            return base.Channel.facturasResumen(request);
        }
        
        public System.Xml.Linq.XElement facturasResumen(int año, int mes) {
            Inventario.ServiceReference1.facturasResumenRequest inValue = new Inventario.ServiceReference1.facturasResumenRequest();
            inValue.Body = new Inventario.ServiceReference1.facturasResumenRequestBody();
            inValue.Body.año = año;
            inValue.Body.mes = mes;
            Inventario.ServiceReference1.facturasResumenResponse retVal = ((Inventario.ServiceReference1.ServiceSoap)(this)).facturasResumen(inValue);
            return retVal.Body.facturasResumenResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Inventario.ServiceReference1.consultarActualizacionResponse Inventario.ServiceReference1.ServiceSoap.consultarActualizacion(Inventario.ServiceReference1.consultarActualizacionRequest request) {
            return base.Channel.consultarActualizacion(request);
        }
        
        public string consultarActualizacion() {
            Inventario.ServiceReference1.consultarActualizacionRequest inValue = new Inventario.ServiceReference1.consultarActualizacionRequest();
            inValue.Body = new Inventario.ServiceReference1.consultarActualizacionRequestBody();
            Inventario.ServiceReference1.consultarActualizacionResponse retVal = ((Inventario.ServiceReference1.ServiceSoap)(this)).consultarActualizacion(inValue);
            return retVal.Body.consultarActualizacionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Inventario.ServiceReference1.subirActualizacionAServidorResponse Inventario.ServiceReference1.ServiceSoap.subirActualizacionAServidor(Inventario.ServiceReference1.subirActualizacionAServidorRequest request) {
            return base.Channel.subirActualizacionAServidor(request);
        }
        
        public bool subirActualizacionAServidor(string version) {
            Inventario.ServiceReference1.subirActualizacionAServidorRequest inValue = new Inventario.ServiceReference1.subirActualizacionAServidorRequest();
            inValue.Body = new Inventario.ServiceReference1.subirActualizacionAServidorRequestBody();
            inValue.Body.version = version;
            Inventario.ServiceReference1.subirActualizacionAServidorResponse retVal = ((Inventario.ServiceReference1.ServiceSoap)(this)).subirActualizacionAServidor(inValue);
            return retVal.Body.subirActualizacionAServidorResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Inventario.ServiceReference1.IngresarFacturaIngresoResponse Inventario.ServiceReference1.ServiceSoap.IngresarFacturaIngreso(Inventario.ServiceReference1.IngresarFacturaIngresoRequest request) {
            return base.Channel.IngresarFacturaIngreso(request);
        }
        
        public bool IngresarFacturaIngreso(System.Xml.Linq.XElement factura) {
            Inventario.ServiceReference1.IngresarFacturaIngresoRequest inValue = new Inventario.ServiceReference1.IngresarFacturaIngresoRequest();
            inValue.Body = new Inventario.ServiceReference1.IngresarFacturaIngresoRequestBody();
            inValue.Body.factura = factura;
            Inventario.ServiceReference1.IngresarFacturaIngresoResponse retVal = ((Inventario.ServiceReference1.ServiceSoap)(this)).IngresarFacturaIngreso(inValue);
            return retVal.Body.IngresarFacturaIngresoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Inventario.ServiceReference1.facturasIngresoResumenResponse Inventario.ServiceReference1.ServiceSoap.facturasIngresoResumen(Inventario.ServiceReference1.facturasIngresoResumenRequest request) {
            return base.Channel.facturasIngresoResumen(request);
        }
        
        public System.Xml.Linq.XElement facturasIngresoResumen(int año, int mes) {
            Inventario.ServiceReference1.facturasIngresoResumenRequest inValue = new Inventario.ServiceReference1.facturasIngresoResumenRequest();
            inValue.Body = new Inventario.ServiceReference1.facturasIngresoResumenRequestBody();
            inValue.Body.año = año;
            inValue.Body.mes = mes;
            Inventario.ServiceReference1.facturasIngresoResumenResponse retVal = ((Inventario.ServiceReference1.ServiceSoap)(this)).facturasIngresoResumen(inValue);
            return retVal.Body.facturasIngresoResumenResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Inventario.ServiceReference1.ingresoPMPResponse Inventario.ServiceReference1.ServiceSoap.ingresoPMP(Inventario.ServiceReference1.ingresoPMPRequest request) {
            return base.Channel.ingresoPMP(request);
        }
        
        public bool ingresoPMP(string NP, int NoE, int EoS, int cantidad, int precioFTR, int precioEXP, string moneda) {
            Inventario.ServiceReference1.ingresoPMPRequest inValue = new Inventario.ServiceReference1.ingresoPMPRequest();
            inValue.Body = new Inventario.ServiceReference1.ingresoPMPRequestBody();
            inValue.Body.NP = NP;
            inValue.Body.NoE = NoE;
            inValue.Body.EoS = EoS;
            inValue.Body.cantidad = cantidad;
            inValue.Body.precioFTR = precioFTR;
            inValue.Body.precioEXP = precioEXP;
            inValue.Body.moneda = moneda;
            Inventario.ServiceReference1.ingresoPMPResponse retVal = ((Inventario.ServiceReference1.ServiceSoap)(this)).ingresoPMP(inValue);
            return retVal.Body.ingresoPMPResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Inventario.ServiceReference1.obtenerPMPResponse Inventario.ServiceReference1.ServiceSoap.obtenerPMP(Inventario.ServiceReference1.obtenerPMPRequest request) {
            return base.Channel.obtenerPMP(request);
        }
        
        public System.Xml.Linq.XElement obtenerPMP() {
            Inventario.ServiceReference1.obtenerPMPRequest inValue = new Inventario.ServiceReference1.obtenerPMPRequest();
            inValue.Body = new Inventario.ServiceReference1.obtenerPMPRequestBody();
            Inventario.ServiceReference1.obtenerPMPResponse retVal = ((Inventario.ServiceReference1.ServiceSoap)(this)).obtenerPMP(inValue);
            return retVal.Body.obtenerPMPResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Inventario.ServiceReference1.uploadFileResponse Inventario.ServiceReference1.ServiceSoap.uploadFile(Inventario.ServiceReference1.uploadFileRequest request) {
            return base.Channel.uploadFile(request);
        }
        
        public bool uploadFile(string name) {
            Inventario.ServiceReference1.uploadFileRequest inValue = new Inventario.ServiceReference1.uploadFileRequest();
            inValue.Body = new Inventario.ServiceReference1.uploadFileRequestBody();
            inValue.Body.name = name;
            Inventario.ServiceReference1.uploadFileResponse retVal = ((Inventario.ServiceReference1.ServiceSoap)(this)).uploadFile(inValue);
            return retVal.Body.uploadFileResult;
        }
    }
}
