//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace actualizadorVARELEC.servicioActualizador {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="servicioActualizador.WebServiceSoap")]
    public interface WebServiceSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        actualizadorVARELEC.servicioActualizador.HelloWorldResponse HelloWorld(actualizadorVARELEC.servicioActualizador.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name usuario from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/escribirMemo", ReplyAction="*")]
        actualizadorVARELEC.servicioActualizador.escribirMemoResponse escribirMemo(actualizadorVARELEC.servicioActualizador.escribirMemoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/estado", ReplyAction="*")]
        int estado();
        
        // CODEGEN: Generating message contract since element name obtenerMemosGenralesResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/obtenerMemosGenrales", ReplyAction="*")]
        actualizadorVARELEC.servicioActualizador.obtenerMemosGenralesResponse obtenerMemosGenrales(actualizadorVARELEC.servicioActualizador.obtenerMemosGenralesRequest request);
        
        // CODEGEN: Generating message contract since element name cotizacion from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/guardarCotizacion", ReplyAction="*")]
        actualizadorVARELEC.servicioActualizador.guardarCotizacionResponse guardarCotizacion(actualizadorVARELEC.servicioActualizador.guardarCotizacionRequest request);
        
        // CODEGEN: Generating message contract since element name listaCotizacionesResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/listaCotizaciones", ReplyAction="*")]
        actualizadorVARELEC.servicioActualizador.listaCotizacionesResponse listaCotizaciones(actualizadorVARELEC.servicioActualizador.listaCotizacionesRequest request);
        
        // CODEGEN: Generating message contract since element name obtenerFacturaResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/obtenerFactura", ReplyAction="*")]
        actualizadorVARELEC.servicioActualizador.obtenerFacturaResponse obtenerFactura(actualizadorVARELEC.servicioActualizador.obtenerFacturaRequest request);
        
        // CODEGEN: Generating message contract since element name indicadoresEconomicosResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/indicadoresEconomicos", ReplyAction="*")]
        actualizadorVARELEC.servicioActualizador.indicadoresEconomicosResponse indicadoresEconomicos(actualizadorVARELEC.servicioActualizador.indicadoresEconomicosRequest request);
        
        // CODEGEN: Generating message contract since element name dolar from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/setearIndicadoresEconomicos", ReplyAction="*")]
        actualizadorVARELEC.servicioActualizador.setearIndicadoresEconomicosResponse setearIndicadoresEconomicos(actualizadorVARELEC.servicioActualizador.setearIndicadoresEconomicosRequest request);
        
        // CODEGEN: Generating message contract since element name factura from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ingresarFacturaLiberada", ReplyAction="*")]
        actualizadorVARELEC.servicioActualizador.ingresarFacturaLiberadaResponse ingresarFacturaLiberada(actualizadorVARELEC.servicioActualizador.ingresarFacturaLiberadaRequest request);
        
        // CODEGEN: Generating message contract since element name ingresarFacturaPorCotizacionResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ingresarFacturaPorCotizacion", ReplyAction="*")]
        actualizadorVARELEC.servicioActualizador.ingresarFacturaPorCotizacionResponse ingresarFacturaPorCotizacion(actualizadorVARELEC.servicioActualizador.ingresarFacturaPorCotizacionRequest request);
        
        // CODEGEN: Generating message contract since element name facturasResumenResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/facturasResumen", ReplyAction="*")]
        actualizadorVARELEC.servicioActualizador.facturasResumenResponse facturasResumen(actualizadorVARELEC.servicioActualizador.facturasResumenRequest request);
        
        // CODEGEN: Generating message contract since element name version from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/subirActualizacion", ReplyAction="*")]
        actualizadorVARELEC.servicioActualizador.subirActualizacionResponse subirActualizacion(actualizadorVARELEC.servicioActualizador.subirActualizacionRequest request);
        
        // CODEGEN: Generating message contract since element name consultarActualizacionResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/consultarActualizacion", ReplyAction="*")]
        actualizadorVARELEC.servicioActualizador.consultarActualizacionResponse consultarActualizacion(actualizadorVARELEC.servicioActualizador.consultarActualizacionRequest request);
        
        // CODEGEN: Generating message contract since element name descargarActualizacionResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/descargarActualizacion", ReplyAction="*")]
        actualizadorVARELEC.servicioActualizador.descargarActualizacionResponse descargarActualizacion(actualizadorVARELEC.servicioActualizador.descargarActualizacionRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public actualizadorVARELEC.servicioActualizador.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(actualizadorVARELEC.servicioActualizador.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public actualizadorVARELEC.servicioActualizador.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(actualizadorVARELEC.servicioActualizador.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class escribirMemoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="escribirMemo", Namespace="http://tempuri.org/", Order=0)]
        public actualizadorVARELEC.servicioActualizador.escribirMemoRequestBody Body;
        
        public escribirMemoRequest() {
        }
        
        public escribirMemoRequest(actualizadorVARELEC.servicioActualizador.escribirMemoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class escribirMemoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string entrada;
        
        public escribirMemoRequestBody() {
        }
        
        public escribirMemoRequestBody(string usuario, string entrada) {
            this.usuario = usuario;
            this.entrada = entrada;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class escribirMemoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="escribirMemoResponse", Namespace="http://tempuri.org/", Order=0)]
        public actualizadorVARELEC.servicioActualizador.escribirMemoResponseBody Body;
        
        public escribirMemoResponse() {
        }
        
        public escribirMemoResponse(actualizadorVARELEC.servicioActualizador.escribirMemoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class escribirMemoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool escribirMemoResult;
        
        public escribirMemoResponseBody() {
        }
        
        public escribirMemoResponseBody(bool escribirMemoResult) {
            this.escribirMemoResult = escribirMemoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class obtenerMemosGenralesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="obtenerMemosGenrales", Namespace="http://tempuri.org/", Order=0)]
        public actualizadorVARELEC.servicioActualizador.obtenerMemosGenralesRequestBody Body;
        
        public obtenerMemosGenralesRequest() {
        }
        
        public obtenerMemosGenralesRequest(actualizadorVARELEC.servicioActualizador.obtenerMemosGenralesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class obtenerMemosGenralesRequestBody {
        
        public obtenerMemosGenralesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class obtenerMemosGenralesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="obtenerMemosGenralesResponse", Namespace="http://tempuri.org/", Order=0)]
        public actualizadorVARELEC.servicioActualizador.obtenerMemosGenralesResponseBody Body;
        
        public obtenerMemosGenralesResponse() {
        }
        
        public obtenerMemosGenralesResponse(actualizadorVARELEC.servicioActualizador.obtenerMemosGenralesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class obtenerMemosGenralesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement obtenerMemosGenralesResult;
        
        public obtenerMemosGenralesResponseBody() {
        }
        
        public obtenerMemosGenralesResponseBody(System.Xml.Linq.XElement obtenerMemosGenralesResult) {
            this.obtenerMemosGenralesResult = obtenerMemosGenralesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class guardarCotizacionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="guardarCotizacion", Namespace="http://tempuri.org/", Order=0)]
        public actualizadorVARELEC.servicioActualizador.guardarCotizacionRequestBody Body;
        
        public guardarCotizacionRequest() {
        }
        
        public guardarCotizacionRequest(actualizadorVARELEC.servicioActualizador.guardarCotizacionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class guardarCotizacionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement cotizacion;
        
        public guardarCotizacionRequestBody() {
        }
        
        public guardarCotizacionRequestBody(System.Xml.Linq.XElement cotizacion) {
            this.cotizacion = cotizacion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class guardarCotizacionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="guardarCotizacionResponse", Namespace="http://tempuri.org/", Order=0)]
        public actualizadorVARELEC.servicioActualizador.guardarCotizacionResponseBody Body;
        
        public guardarCotizacionResponse() {
        }
        
        public guardarCotizacionResponse(actualizadorVARELEC.servicioActualizador.guardarCotizacionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class guardarCotizacionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int guardarCotizacionResult;
        
        public guardarCotizacionResponseBody() {
        }
        
        public guardarCotizacionResponseBody(int guardarCotizacionResult) {
            this.guardarCotizacionResult = guardarCotizacionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class listaCotizacionesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="listaCotizaciones", Namespace="http://tempuri.org/", Order=0)]
        public actualizadorVARELEC.servicioActualizador.listaCotizacionesRequestBody Body;
        
        public listaCotizacionesRequest() {
        }
        
        public listaCotizacionesRequest(actualizadorVARELEC.servicioActualizador.listaCotizacionesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class listaCotizacionesRequestBody {
        
        public listaCotizacionesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class listaCotizacionesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="listaCotizacionesResponse", Namespace="http://tempuri.org/", Order=0)]
        public actualizadorVARELEC.servicioActualizador.listaCotizacionesResponseBody Body;
        
        public listaCotizacionesResponse() {
        }
        
        public listaCotizacionesResponse(actualizadorVARELEC.servicioActualizador.listaCotizacionesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class listaCotizacionesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement listaCotizacionesResult;
        
        public listaCotizacionesResponseBody() {
        }
        
        public listaCotizacionesResponseBody(System.Xml.Linq.XElement listaCotizacionesResult) {
            this.listaCotizacionesResult = listaCotizacionesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class obtenerFacturaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="obtenerFactura", Namespace="http://tempuri.org/", Order=0)]
        public actualizadorVARELEC.servicioActualizador.obtenerFacturaRequestBody Body;
        
        public obtenerFacturaRequest() {
        }
        
        public obtenerFacturaRequest(actualizadorVARELEC.servicioActualizador.obtenerFacturaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class obtenerFacturaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int numero;
        
        public obtenerFacturaRequestBody() {
        }
        
        public obtenerFacturaRequestBody(int numero) {
            this.numero = numero;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class obtenerFacturaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="obtenerFacturaResponse", Namespace="http://tempuri.org/", Order=0)]
        public actualizadorVARELEC.servicioActualizador.obtenerFacturaResponseBody Body;
        
        public obtenerFacturaResponse() {
        }
        
        public obtenerFacturaResponse(actualizadorVARELEC.servicioActualizador.obtenerFacturaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class obtenerFacturaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement obtenerFacturaResult;
        
        public obtenerFacturaResponseBody() {
        }
        
        public obtenerFacturaResponseBody(System.Xml.Linq.XElement obtenerFacturaResult) {
            this.obtenerFacturaResult = obtenerFacturaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class indicadoresEconomicosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="indicadoresEconomicos", Namespace="http://tempuri.org/", Order=0)]
        public actualizadorVARELEC.servicioActualizador.indicadoresEconomicosRequestBody Body;
        
        public indicadoresEconomicosRequest() {
        }
        
        public indicadoresEconomicosRequest(actualizadorVARELEC.servicioActualizador.indicadoresEconomicosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class indicadoresEconomicosRequestBody {
        
        public indicadoresEconomicosRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class indicadoresEconomicosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="indicadoresEconomicosResponse", Namespace="http://tempuri.org/", Order=0)]
        public actualizadorVARELEC.servicioActualizador.indicadoresEconomicosResponseBody Body;
        
        public indicadoresEconomicosResponse() {
        }
        
        public indicadoresEconomicosResponse(actualizadorVARELEC.servicioActualizador.indicadoresEconomicosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class indicadoresEconomicosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement indicadoresEconomicosResult;
        
        public indicadoresEconomicosResponseBody() {
        }
        
        public indicadoresEconomicosResponseBody(System.Xml.Linq.XElement indicadoresEconomicosResult) {
            this.indicadoresEconomicosResult = indicadoresEconomicosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class setearIndicadoresEconomicosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="setearIndicadoresEconomicos", Namespace="http://tempuri.org/", Order=0)]
        public actualizadorVARELEC.servicioActualizador.setearIndicadoresEconomicosRequestBody Body;
        
        public setearIndicadoresEconomicosRequest() {
        }
        
        public setearIndicadoresEconomicosRequest(actualizadorVARELEC.servicioActualizador.setearIndicadoresEconomicosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class setearIndicadoresEconomicosRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string dolar;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string euro;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string importe;
        
        public setearIndicadoresEconomicosRequestBody() {
        }
        
        public setearIndicadoresEconomicosRequestBody(string dolar, string euro, string importe) {
            this.dolar = dolar;
            this.euro = euro;
            this.importe = importe;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class setearIndicadoresEconomicosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="setearIndicadoresEconomicosResponse", Namespace="http://tempuri.org/", Order=0)]
        public actualizadorVARELEC.servicioActualizador.setearIndicadoresEconomicosResponseBody Body;
        
        public setearIndicadoresEconomicosResponse() {
        }
        
        public setearIndicadoresEconomicosResponse(actualizadorVARELEC.servicioActualizador.setearIndicadoresEconomicosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class setearIndicadoresEconomicosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool setearIndicadoresEconomicosResult;
        
        public setearIndicadoresEconomicosResponseBody() {
        }
        
        public setearIndicadoresEconomicosResponseBody(bool setearIndicadoresEconomicosResult) {
            this.setearIndicadoresEconomicosResult = setearIndicadoresEconomicosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ingresarFacturaLiberadaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ingresarFacturaLiberada", Namespace="http://tempuri.org/", Order=0)]
        public actualizadorVARELEC.servicioActualizador.ingresarFacturaLiberadaRequestBody Body;
        
        public ingresarFacturaLiberadaRequest() {
        }
        
        public ingresarFacturaLiberadaRequest(actualizadorVARELEC.servicioActualizador.ingresarFacturaLiberadaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ingresarFacturaLiberadaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement factura;
        
        public ingresarFacturaLiberadaRequestBody() {
        }
        
        public ingresarFacturaLiberadaRequestBody(System.Xml.Linq.XElement factura) {
            this.factura = factura;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ingresarFacturaLiberadaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ingresarFacturaLiberadaResponse", Namespace="http://tempuri.org/", Order=0)]
        public actualizadorVARELEC.servicioActualizador.ingresarFacturaLiberadaResponseBody Body;
        
        public ingresarFacturaLiberadaResponse() {
        }
        
        public ingresarFacturaLiberadaResponse(actualizadorVARELEC.servicioActualizador.ingresarFacturaLiberadaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ingresarFacturaLiberadaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ingresarFacturaLiberadaResult;
        
        public ingresarFacturaLiberadaResponseBody() {
        }
        
        public ingresarFacturaLiberadaResponseBody(bool ingresarFacturaLiberadaResult) {
            this.ingresarFacturaLiberadaResult = ingresarFacturaLiberadaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ingresarFacturaPorCotizacionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ingresarFacturaPorCotizacion", Namespace="http://tempuri.org/", Order=0)]
        public actualizadorVARELEC.servicioActualizador.ingresarFacturaPorCotizacionRequestBody Body;
        
        public ingresarFacturaPorCotizacionRequest() {
        }
        
        public ingresarFacturaPorCotizacionRequest(actualizadorVARELEC.servicioActualizador.ingresarFacturaPorCotizacionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ingresarFacturaPorCotizacionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int identificacion;
        
        public ingresarFacturaPorCotizacionRequestBody() {
        }
        
        public ingresarFacturaPorCotizacionRequestBody(int identificacion) {
            this.identificacion = identificacion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ingresarFacturaPorCotizacionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ingresarFacturaPorCotizacionResponse", Namespace="http://tempuri.org/", Order=0)]
        public actualizadorVARELEC.servicioActualizador.ingresarFacturaPorCotizacionResponseBody Body;
        
        public ingresarFacturaPorCotizacionResponse() {
        }
        
        public ingresarFacturaPorCotizacionResponse(actualizadorVARELEC.servicioActualizador.ingresarFacturaPorCotizacionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ingresarFacturaPorCotizacionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ingresarFacturaPorCotizacionResult;
        
        public ingresarFacturaPorCotizacionResponseBody() {
        }
        
        public ingresarFacturaPorCotizacionResponseBody(string ingresarFacturaPorCotizacionResult) {
            this.ingresarFacturaPorCotizacionResult = ingresarFacturaPorCotizacionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class facturasResumenRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="facturasResumen", Namespace="http://tempuri.org/", Order=0)]
        public actualizadorVARELEC.servicioActualizador.facturasResumenRequestBody Body;
        
        public facturasResumenRequest() {
        }
        
        public facturasResumenRequest(actualizadorVARELEC.servicioActualizador.facturasResumenRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class facturasResumenRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int año;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int mes;
        
        public facturasResumenRequestBody() {
        }
        
        public facturasResumenRequestBody(int año, int mes) {
            this.año = año;
            this.mes = mes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class facturasResumenResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="facturasResumenResponse", Namespace="http://tempuri.org/", Order=0)]
        public actualizadorVARELEC.servicioActualizador.facturasResumenResponseBody Body;
        
        public facturasResumenResponse() {
        }
        
        public facturasResumenResponse(actualizadorVARELEC.servicioActualizador.facturasResumenResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class facturasResumenResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement facturasResumenResult;
        
        public facturasResumenResponseBody() {
        }
        
        public facturasResumenResponseBody(System.Xml.Linq.XElement facturasResumenResult) {
            this.facturasResumenResult = facturasResumenResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class subirActualizacionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="subirActualizacion", Namespace="http://tempuri.org/", Order=0)]
        public actualizadorVARELEC.servicioActualizador.subirActualizacionRequestBody Body;
        
        public subirActualizacionRequest() {
        }
        
        public subirActualizacionRequest(actualizadorVARELEC.servicioActualizador.subirActualizacionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class subirActualizacionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string version;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public byte[] programa;
        
        public subirActualizacionRequestBody() {
        }
        
        public subirActualizacionRequestBody(string version, byte[] programa) {
            this.version = version;
            this.programa = programa;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class subirActualizacionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="subirActualizacionResponse", Namespace="http://tempuri.org/", Order=0)]
        public actualizadorVARELEC.servicioActualizador.subirActualizacionResponseBody Body;
        
        public subirActualizacionResponse() {
        }
        
        public subirActualizacionResponse(actualizadorVARELEC.servicioActualizador.subirActualizacionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class subirActualizacionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool subirActualizacionResult;
        
        public subirActualizacionResponseBody() {
        }
        
        public subirActualizacionResponseBody(bool subirActualizacionResult) {
            this.subirActualizacionResult = subirActualizacionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultarActualizacionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="consultarActualizacion", Namespace="http://tempuri.org/", Order=0)]
        public actualizadorVARELEC.servicioActualizador.consultarActualizacionRequestBody Body;
        
        public consultarActualizacionRequest() {
        }
        
        public consultarActualizacionRequest(actualizadorVARELEC.servicioActualizador.consultarActualizacionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class consultarActualizacionRequestBody {
        
        public consultarActualizacionRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultarActualizacionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="consultarActualizacionResponse", Namespace="http://tempuri.org/", Order=0)]
        public actualizadorVARELEC.servicioActualizador.consultarActualizacionResponseBody Body;
        
        public consultarActualizacionResponse() {
        }
        
        public consultarActualizacionResponse(actualizadorVARELEC.servicioActualizador.consultarActualizacionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class consultarActualizacionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string consultarActualizacionResult;
        
        public consultarActualizacionResponseBody() {
        }
        
        public consultarActualizacionResponseBody(string consultarActualizacionResult) {
            this.consultarActualizacionResult = consultarActualizacionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class descargarActualizacionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="descargarActualizacion", Namespace="http://tempuri.org/", Order=0)]
        public actualizadorVARELEC.servicioActualizador.descargarActualizacionRequestBody Body;
        
        public descargarActualizacionRequest() {
        }
        
        public descargarActualizacionRequest(actualizadorVARELEC.servicioActualizador.descargarActualizacionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class descargarActualizacionRequestBody {
        
        public descargarActualizacionRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class descargarActualizacionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="descargarActualizacionResponse", Namespace="http://tempuri.org/", Order=0)]
        public actualizadorVARELEC.servicioActualizador.descargarActualizacionResponseBody Body;
        
        public descargarActualizacionResponse() {
        }
        
        public descargarActualizacionResponse(actualizadorVARELEC.servicioActualizador.descargarActualizacionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class descargarActualizacionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] descargarActualizacionResult;
        
        public descargarActualizacionResponseBody() {
        }
        
        public descargarActualizacionResponseBody(byte[] descargarActualizacionResult) {
            this.descargarActualizacionResult = descargarActualizacionResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : actualizadorVARELEC.servicioActualizador.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<actualizadorVARELEC.servicioActualizador.WebServiceSoap>, actualizadorVARELEC.servicioActualizador.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        actualizadorVARELEC.servicioActualizador.HelloWorldResponse actualizadorVARELEC.servicioActualizador.WebServiceSoap.HelloWorld(actualizadorVARELEC.servicioActualizador.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            actualizadorVARELEC.servicioActualizador.HelloWorldRequest inValue = new actualizadorVARELEC.servicioActualizador.HelloWorldRequest();
            inValue.Body = new actualizadorVARELEC.servicioActualizador.HelloWorldRequestBody();
            actualizadorVARELEC.servicioActualizador.HelloWorldResponse retVal = ((actualizadorVARELEC.servicioActualizador.WebServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        actualizadorVARELEC.servicioActualizador.escribirMemoResponse actualizadorVARELEC.servicioActualizador.WebServiceSoap.escribirMemo(actualizadorVARELEC.servicioActualizador.escribirMemoRequest request) {
            return base.Channel.escribirMemo(request);
        }
        
        public bool escribirMemo(string usuario, string entrada) {
            actualizadorVARELEC.servicioActualizador.escribirMemoRequest inValue = new actualizadorVARELEC.servicioActualizador.escribirMemoRequest();
            inValue.Body = new actualizadorVARELEC.servicioActualizador.escribirMemoRequestBody();
            inValue.Body.usuario = usuario;
            inValue.Body.entrada = entrada;
            actualizadorVARELEC.servicioActualizador.escribirMemoResponse retVal = ((actualizadorVARELEC.servicioActualizador.WebServiceSoap)(this)).escribirMemo(inValue);
            return retVal.Body.escribirMemoResult;
        }
        
        public int estado() {
            return base.Channel.estado();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        actualizadorVARELEC.servicioActualizador.obtenerMemosGenralesResponse actualizadorVARELEC.servicioActualizador.WebServiceSoap.obtenerMemosGenrales(actualizadorVARELEC.servicioActualizador.obtenerMemosGenralesRequest request) {
            return base.Channel.obtenerMemosGenrales(request);
        }
        
        public System.Xml.Linq.XElement obtenerMemosGenrales() {
            actualizadorVARELEC.servicioActualizador.obtenerMemosGenralesRequest inValue = new actualizadorVARELEC.servicioActualizador.obtenerMemosGenralesRequest();
            inValue.Body = new actualizadorVARELEC.servicioActualizador.obtenerMemosGenralesRequestBody();
            actualizadorVARELEC.servicioActualizador.obtenerMemosGenralesResponse retVal = ((actualizadorVARELEC.servicioActualizador.WebServiceSoap)(this)).obtenerMemosGenrales(inValue);
            return retVal.Body.obtenerMemosGenralesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        actualizadorVARELEC.servicioActualizador.guardarCotizacionResponse actualizadorVARELEC.servicioActualizador.WebServiceSoap.guardarCotizacion(actualizadorVARELEC.servicioActualizador.guardarCotizacionRequest request) {
            return base.Channel.guardarCotizacion(request);
        }
        
        public int guardarCotizacion(System.Xml.Linq.XElement cotizacion) {
            actualizadorVARELEC.servicioActualizador.guardarCotizacionRequest inValue = new actualizadorVARELEC.servicioActualizador.guardarCotizacionRequest();
            inValue.Body = new actualizadorVARELEC.servicioActualizador.guardarCotizacionRequestBody();
            inValue.Body.cotizacion = cotizacion;
            actualizadorVARELEC.servicioActualizador.guardarCotizacionResponse retVal = ((actualizadorVARELEC.servicioActualizador.WebServiceSoap)(this)).guardarCotizacion(inValue);
            return retVal.Body.guardarCotizacionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        actualizadorVARELEC.servicioActualizador.listaCotizacionesResponse actualizadorVARELEC.servicioActualizador.WebServiceSoap.listaCotizaciones(actualizadorVARELEC.servicioActualizador.listaCotizacionesRequest request) {
            return base.Channel.listaCotizaciones(request);
        }
        
        public System.Xml.Linq.XElement listaCotizaciones() {
            actualizadorVARELEC.servicioActualizador.listaCotizacionesRequest inValue = new actualizadorVARELEC.servicioActualizador.listaCotizacionesRequest();
            inValue.Body = new actualizadorVARELEC.servicioActualizador.listaCotizacionesRequestBody();
            actualizadorVARELEC.servicioActualizador.listaCotizacionesResponse retVal = ((actualizadorVARELEC.servicioActualizador.WebServiceSoap)(this)).listaCotizaciones(inValue);
            return retVal.Body.listaCotizacionesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        actualizadorVARELEC.servicioActualizador.obtenerFacturaResponse actualizadorVARELEC.servicioActualizador.WebServiceSoap.obtenerFactura(actualizadorVARELEC.servicioActualizador.obtenerFacturaRequest request) {
            return base.Channel.obtenerFactura(request);
        }
        
        public System.Xml.Linq.XElement obtenerFactura(int numero) {
            actualizadorVARELEC.servicioActualizador.obtenerFacturaRequest inValue = new actualizadorVARELEC.servicioActualizador.obtenerFacturaRequest();
            inValue.Body = new actualizadorVARELEC.servicioActualizador.obtenerFacturaRequestBody();
            inValue.Body.numero = numero;
            actualizadorVARELEC.servicioActualizador.obtenerFacturaResponse retVal = ((actualizadorVARELEC.servicioActualizador.WebServiceSoap)(this)).obtenerFactura(inValue);
            return retVal.Body.obtenerFacturaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        actualizadorVARELEC.servicioActualizador.indicadoresEconomicosResponse actualizadorVARELEC.servicioActualizador.WebServiceSoap.indicadoresEconomicos(actualizadorVARELEC.servicioActualizador.indicadoresEconomicosRequest request) {
            return base.Channel.indicadoresEconomicos(request);
        }
        
        public System.Xml.Linq.XElement indicadoresEconomicos() {
            actualizadorVARELEC.servicioActualizador.indicadoresEconomicosRequest inValue = new actualizadorVARELEC.servicioActualizador.indicadoresEconomicosRequest();
            inValue.Body = new actualizadorVARELEC.servicioActualizador.indicadoresEconomicosRequestBody();
            actualizadorVARELEC.servicioActualizador.indicadoresEconomicosResponse retVal = ((actualizadorVARELEC.servicioActualizador.WebServiceSoap)(this)).indicadoresEconomicos(inValue);
            return retVal.Body.indicadoresEconomicosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        actualizadorVARELEC.servicioActualizador.setearIndicadoresEconomicosResponse actualizadorVARELEC.servicioActualizador.WebServiceSoap.setearIndicadoresEconomicos(actualizadorVARELEC.servicioActualizador.setearIndicadoresEconomicosRequest request) {
            return base.Channel.setearIndicadoresEconomicos(request);
        }
        
        public bool setearIndicadoresEconomicos(string dolar, string euro, string importe) {
            actualizadorVARELEC.servicioActualizador.setearIndicadoresEconomicosRequest inValue = new actualizadorVARELEC.servicioActualizador.setearIndicadoresEconomicosRequest();
            inValue.Body = new actualizadorVARELEC.servicioActualizador.setearIndicadoresEconomicosRequestBody();
            inValue.Body.dolar = dolar;
            inValue.Body.euro = euro;
            inValue.Body.importe = importe;
            actualizadorVARELEC.servicioActualizador.setearIndicadoresEconomicosResponse retVal = ((actualizadorVARELEC.servicioActualizador.WebServiceSoap)(this)).setearIndicadoresEconomicos(inValue);
            return retVal.Body.setearIndicadoresEconomicosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        actualizadorVARELEC.servicioActualizador.ingresarFacturaLiberadaResponse actualizadorVARELEC.servicioActualizador.WebServiceSoap.ingresarFacturaLiberada(actualizadorVARELEC.servicioActualizador.ingresarFacturaLiberadaRequest request) {
            return base.Channel.ingresarFacturaLiberada(request);
        }
        
        public bool ingresarFacturaLiberada(System.Xml.Linq.XElement factura) {
            actualizadorVARELEC.servicioActualizador.ingresarFacturaLiberadaRequest inValue = new actualizadorVARELEC.servicioActualizador.ingresarFacturaLiberadaRequest();
            inValue.Body = new actualizadorVARELEC.servicioActualizador.ingresarFacturaLiberadaRequestBody();
            inValue.Body.factura = factura;
            actualizadorVARELEC.servicioActualizador.ingresarFacturaLiberadaResponse retVal = ((actualizadorVARELEC.servicioActualizador.WebServiceSoap)(this)).ingresarFacturaLiberada(inValue);
            return retVal.Body.ingresarFacturaLiberadaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        actualizadorVARELEC.servicioActualizador.ingresarFacturaPorCotizacionResponse actualizadorVARELEC.servicioActualizador.WebServiceSoap.ingresarFacturaPorCotizacion(actualizadorVARELEC.servicioActualizador.ingresarFacturaPorCotizacionRequest request) {
            return base.Channel.ingresarFacturaPorCotizacion(request);
        }
        
        public string ingresarFacturaPorCotizacion(int identificacion) {
            actualizadorVARELEC.servicioActualizador.ingresarFacturaPorCotizacionRequest inValue = new actualizadorVARELEC.servicioActualizador.ingresarFacturaPorCotizacionRequest();
            inValue.Body = new actualizadorVARELEC.servicioActualizador.ingresarFacturaPorCotizacionRequestBody();
            inValue.Body.identificacion = identificacion;
            actualizadorVARELEC.servicioActualizador.ingresarFacturaPorCotizacionResponse retVal = ((actualizadorVARELEC.servicioActualizador.WebServiceSoap)(this)).ingresarFacturaPorCotizacion(inValue);
            return retVal.Body.ingresarFacturaPorCotizacionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        actualizadorVARELEC.servicioActualizador.facturasResumenResponse actualizadorVARELEC.servicioActualizador.WebServiceSoap.facturasResumen(actualizadorVARELEC.servicioActualizador.facturasResumenRequest request) {
            return base.Channel.facturasResumen(request);
        }
        
        public System.Xml.Linq.XElement facturasResumen(int año, int mes) {
            actualizadorVARELEC.servicioActualizador.facturasResumenRequest inValue = new actualizadorVARELEC.servicioActualizador.facturasResumenRequest();
            inValue.Body = new actualizadorVARELEC.servicioActualizador.facturasResumenRequestBody();
            inValue.Body.año = año;
            inValue.Body.mes = mes;
            actualizadorVARELEC.servicioActualizador.facturasResumenResponse retVal = ((actualizadorVARELEC.servicioActualizador.WebServiceSoap)(this)).facturasResumen(inValue);
            return retVal.Body.facturasResumenResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        actualizadorVARELEC.servicioActualizador.subirActualizacionResponse actualizadorVARELEC.servicioActualizador.WebServiceSoap.subirActualizacion(actualizadorVARELEC.servicioActualizador.subirActualizacionRequest request) {
            return base.Channel.subirActualizacion(request);
        }
        
        public bool subirActualizacion(string version, byte[] programa) {
            actualizadorVARELEC.servicioActualizador.subirActualizacionRequest inValue = new actualizadorVARELEC.servicioActualizador.subirActualizacionRequest();
            inValue.Body = new actualizadorVARELEC.servicioActualizador.subirActualizacionRequestBody();
            inValue.Body.version = version;
            inValue.Body.programa = programa;
            actualizadorVARELEC.servicioActualizador.subirActualizacionResponse retVal = ((actualizadorVARELEC.servicioActualizador.WebServiceSoap)(this)).subirActualizacion(inValue);
            return retVal.Body.subirActualizacionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        actualizadorVARELEC.servicioActualizador.consultarActualizacionResponse actualizadorVARELEC.servicioActualizador.WebServiceSoap.consultarActualizacion(actualizadorVARELEC.servicioActualizador.consultarActualizacionRequest request) {
            return base.Channel.consultarActualizacion(request);
        }
        
        public string consultarActualizacion() {
            actualizadorVARELEC.servicioActualizador.consultarActualizacionRequest inValue = new actualizadorVARELEC.servicioActualizador.consultarActualizacionRequest();
            inValue.Body = new actualizadorVARELEC.servicioActualizador.consultarActualizacionRequestBody();
            actualizadorVARELEC.servicioActualizador.consultarActualizacionResponse retVal = ((actualizadorVARELEC.servicioActualizador.WebServiceSoap)(this)).consultarActualizacion(inValue);
            return retVal.Body.consultarActualizacionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        actualizadorVARELEC.servicioActualizador.descargarActualizacionResponse actualizadorVARELEC.servicioActualizador.WebServiceSoap.descargarActualizacion(actualizadorVARELEC.servicioActualizador.descargarActualizacionRequest request) {
            return base.Channel.descargarActualizacion(request);
        }
        
        public byte[] descargarActualizacion() {
            actualizadorVARELEC.servicioActualizador.descargarActualizacionRequest inValue = new actualizadorVARELEC.servicioActualizador.descargarActualizacionRequest();
            inValue.Body = new actualizadorVARELEC.servicioActualizador.descargarActualizacionRequestBody();
            actualizadorVARELEC.servicioActualizador.descargarActualizacionResponse retVal = ((actualizadorVARELEC.servicioActualizador.WebServiceSoap)(this)).descargarActualizacion(inValue);
            return retVal.Body.descargarActualizacionResult;
        }
    }
}
