//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventario.ServidorVarelec {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServidorVarelec.IServicio")]
    public interface IServicio {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/setearIndicadoresEconomicos", ReplyAction="http://tempuri.org/IServicio/setearIndicadoresEconomicosResponse")]
        bool setearIndicadoresEconomicos(string dolar, string euro, string importe);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ingresarFacturaLiberada", ReplyAction="http://tempuri.org/IServicio/ingresarFacturaLiberadaResponse")]
        bool ingresarFacturaLiberada(System.Xml.Linq.XElement factura);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ingresarFacturaPorCotizacion", ReplyAction="http://tempuri.org/IServicio/ingresarFacturaPorCotizacionResponse")]
        string ingresarFacturaPorCotizacion(int identificacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/facturasResumen", ReplyAction="http://tempuri.org/IServicio/facturasResumenResponse")]
        System.Xml.Linq.XElement facturasResumen(int año, int mes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/consultarActualizacion", ReplyAction="http://tempuri.org/IServicio/consultarActualizacionResponse")]
        string consultarActualizacion();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/subirActualizacionAServidor", ReplyAction="http://tempuri.org/IServicio/subirActualizacionAServidorResponse")]
        bool subirActualizacionAServidor();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/IngresarFacturaIngreso", ReplyAction="http://tempuri.org/IServicio/IngresarFacturaIngresoResponse")]
        bool IngresarFacturaIngreso(System.Xml.Linq.XElement factura);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/facturasIngresoResumen", ReplyAction="http://tempuri.org/IServicio/facturasIngresoResumenResponse")]
        System.Xml.Linq.XElement facturasIngresoResumen(int año, int mes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ingresoPMP", ReplyAction="http://tempuri.org/IServicio/ingresoPMPResponse")]
        bool ingresoPMP(string NP, int NoE, int EoS, int cantidad, int precioFTR, int precioEXP, string moneda);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/obtenerPMP", ReplyAction="http://tempuri.org/IServicio/obtenerPMPResponse")]
        System.Xml.Linq.XElement obtenerPMP();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/uploadFile", ReplyAction="http://tempuri.org/IServicio/uploadFileResponse")]
        bool uploadFile(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/registrarInicio", ReplyAction="http://tempuri.org/IServicio/registrarInicioResponse")]
        bool registrarInicio(string usuario, string dateComplete);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/obtenerHistorialInicios", ReplyAction="http://tempuri.org/IServicio/obtenerHistorialIniciosResponse")]
        System.Xml.Linq.XElement obtenerHistorialInicios();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/online", ReplyAction="http://tempuri.org/IServicio/onlineResponse")]
        bool online();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/inventarioAgregar", ReplyAction="http://tempuri.org/IServicio/inventarioAgregarResponse")]
        int inventarioAgregar(string[] fila);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/inventarioModificar", ReplyAction="http://tempuri.org/IServicio/inventarioModificarResponse")]
        int inventarioModificar(string[] fila);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/inventarioEliminar", ReplyAction="http://tempuri.org/IServicio/inventarioEliminarResponse")]
        int inventarioEliminar(string fila);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/inventarioNVersion", ReplyAction="http://tempuri.org/IServicio/inventarioNVersionResponse")]
        string inventarioNVersion();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/inventarioObtener", ReplyAction="http://tempuri.org/IServicio/inventarioObtenerResponse")]
        System.Xml.Linq.XElement inventarioObtener();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/inventarioErrores", ReplyAction="http://tempuri.org/IServicio/inventarioErroresResponse")]
        System.Xml.Linq.XElement inventarioErrores();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/inventarioErrorUltimo", ReplyAction="http://tempuri.org/IServicio/inventarioErrorUltimoResponse")]
        string inventarioErrorUltimo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/clientesAgregar", ReplyAction="http://tempuri.org/IServicio/clientesAgregarResponse")]
        int clientesAgregar(string[] fila);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/clientesModificar", ReplyAction="http://tempuri.org/IServicio/clientesModificarResponse")]
        int clientesModificar(string[] fila);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/clientesEliminar", ReplyAction="http://tempuri.org/IServicio/clientesEliminarResponse")]
        int clientesEliminar(string fila);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/clientesNVersion", ReplyAction="http://tempuri.org/IServicio/clientesNVersionResponse")]
        string clientesNVersion();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/clientesObtener", ReplyAction="http://tempuri.org/IServicio/clientesObtenerResponse")]
        System.Xml.Linq.XElement clientesObtener();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/clientesErrores", ReplyAction="http://tempuri.org/IServicio/clientesErroresResponse")]
        System.Xml.Linq.XElement clientesErrores();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/clientesErrorUltimo", ReplyAction="http://tempuri.org/IServicio/clientesErrorUltimoResponse")]
        string clientesErrorUltimo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/usuariosAgregar", ReplyAction="http://tempuri.org/IServicio/usuariosAgregarResponse")]
        int usuariosAgregar(string[] fila);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/usuariosModificar", ReplyAction="http://tempuri.org/IServicio/usuariosModificarResponse")]
        int usuariosModificar(string[] fila);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/usuariosEliminar", ReplyAction="http://tempuri.org/IServicio/usuariosEliminarResponse")]
        int usuariosEliminar(string fila);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/usuariosNVersion", ReplyAction="http://tempuri.org/IServicio/usuariosNVersionResponse")]
        string usuariosNVersion();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/usuariosObtener", ReplyAction="http://tempuri.org/IServicio/usuariosObtenerResponse")]
        System.Xml.Linq.XElement usuariosObtener();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/usuariosErrores", ReplyAction="http://tempuri.org/IServicio/usuariosErroresResponse")]
        System.Xml.Linq.XElement usuariosErrores();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/usuariosErrorUltimo", ReplyAction="http://tempuri.org/IServicio/usuariosErrorUltimoResponse")]
        string usuariosErrorUltimo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/escribirMemo", ReplyAction="http://tempuri.org/IServicio/escribirMemoResponse")]
        bool escribirMemo(string usuario, string entrada);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/obtenerMemosGenrales", ReplyAction="http://tempuri.org/IServicio/obtenerMemosGenralesResponse")]
        System.Xml.Linq.XElement obtenerMemosGenrales();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/guardarCotizacion", ReplyAction="http://tempuri.org/IServicio/guardarCotizacionResponse")]
        int guardarCotizacion(System.Xml.Linq.XElement cotizacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/listaCotizaciones", ReplyAction="http://tempuri.org/IServicio/listaCotizacionesResponse")]
        System.Xml.Linq.XElement listaCotizaciones();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/obtenerFactura", ReplyAction="http://tempuri.org/IServicio/obtenerFacturaResponse")]
        System.Xml.Linq.XElement obtenerFactura(int numero);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/indicadoresEconomicos", ReplyAction="http://tempuri.org/IServicio/indicadoresEconomicosResponse")]
        System.Xml.Linq.XElement indicadoresEconomicos();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioChannel : Inventario.ServidorVarelec.IServicio, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioClient : System.ServiceModel.ClientBase<Inventario.ServidorVarelec.IServicio>, Inventario.ServidorVarelec.IServicio {
        
        public ServicioClient() {
        }
        
        public ServicioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool setearIndicadoresEconomicos(string dolar, string euro, string importe) {
            return base.Channel.setearIndicadoresEconomicos(dolar, euro, importe);
        }
        
        public bool ingresarFacturaLiberada(System.Xml.Linq.XElement factura) {
            return base.Channel.ingresarFacturaLiberada(factura);
        }
        
        public string ingresarFacturaPorCotizacion(int identificacion) {
            return base.Channel.ingresarFacturaPorCotizacion(identificacion);
        }
        
        public System.Xml.Linq.XElement facturasResumen(int año, int mes) {
            return base.Channel.facturasResumen(año, mes);
        }
        
        public string consultarActualizacion() {
            return base.Channel.consultarActualizacion();
        }
        
        public bool subirActualizacionAServidor() {
            return base.Channel.subirActualizacionAServidor();
        }
        
        public bool IngresarFacturaIngreso(System.Xml.Linq.XElement factura) {
            return base.Channel.IngresarFacturaIngreso(factura);
        }
        
        public System.Xml.Linq.XElement facturasIngresoResumen(int año, int mes) {
            return base.Channel.facturasIngresoResumen(año, mes);
        }
        
        public bool ingresoPMP(string NP, int NoE, int EoS, int cantidad, int precioFTR, int precioEXP, string moneda) {
            return base.Channel.ingresoPMP(NP, NoE, EoS, cantidad, precioFTR, precioEXP, moneda);
        }
        
        public System.Xml.Linq.XElement obtenerPMP() {
            return base.Channel.obtenerPMP();
        }
        
        public bool uploadFile(string name) {
            return base.Channel.uploadFile(name);
        }
        
        public bool registrarInicio(string usuario, string dateComplete) {
            return base.Channel.registrarInicio(usuario, dateComplete);
        }
        
        public System.Xml.Linq.XElement obtenerHistorialInicios() {
            return base.Channel.obtenerHistorialInicios();
        }
        
        public bool online() {
            return base.Channel.online();
        }
        
        public int inventarioAgregar(string[] fila) {
            return base.Channel.inventarioAgregar(fila);
        }
        
        public int inventarioModificar(string[] fila) {
            return base.Channel.inventarioModificar(fila);
        }
        
        public int inventarioEliminar(string fila) {
            return base.Channel.inventarioEliminar(fila);
        }
        
        public string inventarioNVersion() {
            return base.Channel.inventarioNVersion();
        }
        
        public System.Xml.Linq.XElement inventarioObtener() {
            return base.Channel.inventarioObtener();
        }
        
        public System.Xml.Linq.XElement inventarioErrores() {
            return base.Channel.inventarioErrores();
        }
        
        public string inventarioErrorUltimo() {
            return base.Channel.inventarioErrorUltimo();
        }
        
        public int clientesAgregar(string[] fila) {
            return base.Channel.clientesAgregar(fila);
        }
        
        public int clientesModificar(string[] fila) {
            return base.Channel.clientesModificar(fila);
        }
        
        public int clientesEliminar(string fila) {
            return base.Channel.clientesEliminar(fila);
        }
        
        public string clientesNVersion() {
            return base.Channel.clientesNVersion();
        }
        
        public System.Xml.Linq.XElement clientesObtener() {
            return base.Channel.clientesObtener();
        }
        
        public System.Xml.Linq.XElement clientesErrores() {
            return base.Channel.clientesErrores();
        }
        
        public string clientesErrorUltimo() {
            return base.Channel.clientesErrorUltimo();
        }
        
        public int usuariosAgregar(string[] fila) {
            return base.Channel.usuariosAgregar(fila);
        }
        
        public int usuariosModificar(string[] fila) {
            return base.Channel.usuariosModificar(fila);
        }
        
        public int usuariosEliminar(string fila) {
            return base.Channel.usuariosEliminar(fila);
        }
        
        public string usuariosNVersion() {
            return base.Channel.usuariosNVersion();
        }
        
        public System.Xml.Linq.XElement usuariosObtener() {
            return base.Channel.usuariosObtener();
        }
        
        public System.Xml.Linq.XElement usuariosErrores() {
            return base.Channel.usuariosErrores();
        }
        
        public string usuariosErrorUltimo() {
            return base.Channel.usuariosErrorUltimo();
        }
        
        public bool escribirMemo(string usuario, string entrada) {
            return base.Channel.escribirMemo(usuario, entrada);
        }
        
        public System.Xml.Linq.XElement obtenerMemosGenrales() {
            return base.Channel.obtenerMemosGenrales();
        }
        
        public int guardarCotizacion(System.Xml.Linq.XElement cotizacion) {
            return base.Channel.guardarCotizacion(cotizacion);
        }
        
        public System.Xml.Linq.XElement listaCotizaciones() {
            return base.Channel.listaCotizaciones();
        }
        
        public System.Xml.Linq.XElement obtenerFactura(int numero) {
            return base.Channel.obtenerFactura(numero);
        }
        
        public System.Xml.Linq.XElement indicadoresEconomicos() {
            return base.Channel.indicadoresEconomicos();
        }
    }
}
